### ISSUE TITLE
Bug: TypeError: Cannot read properties of undefined (reading 'moving') on version 3.8.1+

### ISSUE THREAD

**Issue by dnicolson** [OpenWonderLabs/homebridge-switchbot#1050]
### Describe the Bug

The plug-in fails to initialize when using BLE.

### To Reproduce

1. Start Homebridge.

### Expected Behavior

No error.

### Relevant Log Output

```shell
TypeError: Cannot read properties of undefined (reading 'moving')
    at Curtain.getCurrentPostion (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/curtain.ts:841:48)
    at Curtain.BLEparseStatus (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/curtain.ts:385:5)
    at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/curtain.ts:495:11
```

### Config for homebridge-switchbot

```shell
{
    "deviceId": "XXXXXXXXXXXX",
    "configDeviceName": "Curtain",
    "configDeviceType": "Curtain",
    "connectionType": "BLE",
    "curtain": {
        "set_min": 10,
        "set_max": 90,
        "setOpenMode": "1",
        "setCloseMode": "1",
        "hide_lightsensor": false,
        "set_minlux": 1,
        "set_maxlux": 6001
    },
    "maxRetry": 50,
    "logging": "standard"
}
```

### Device and Model

SwitchBot Curtain

### Node.js Version

v18.18.2

### NPM Version

v9.8.1

### Homebridge Version

v1.8.4

### Homebridge Switchbot Plugin Version

v3.8.1

### Homebridge Config UI X Plugin Version

v4.58.0

### Operating System

Raspian

**Comment by donavanbecker** [comment]
Should be resolved in v4.0.0
