### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by setheryb** [OpenWonderLabs/homebridge-switchbot#1078]
### Describe Your Problem

Unable to update to 4.0.0

### Relevant log output

```shell
USER: homebridge
DIR: /volume1/homebridge
CMD: /var/packages/homebridge/target/app/lib/node_modules/homebridge-config-ui-x/scripts/upgrade-install-plugin.sh @switchbot/homebridge-switchbot 4.0.0 /volume1/homebridge/node_modules
Target Version: 4.0.0
Target Path: /volume1/homebridge/node_modules
Downloading @switchbot@homebridge-switchbot-4.0.0.sha256...
Downloading @switchbot@homebridge-switchbot-4.0.0.tar.gz...
#=#=-#
##O#- #
#=#=#   #
                                               0.0%

###
                                 3.8%

########
                                                                     10.5%

################
                                                              20.5%

######################
###                                                         31.8%

#########################
###########                                              45.9%

########################################
###########                               64.6%

###########################
############################################           89.1%

#######################
######################################################### 100.0%

Verifying download...
@switchbot@homebridge-switchbot-4.0.0.tar.gz: OK
@switchbot@homebridge-switchbot-4.0.0.tar.gz: OK

Creating backup...
Backup path: /volume1/homebridge/node_modules/.@switchbot@homebridge-switchbot-4.0.0.bak
Extracting...
***************
Removed extracting info
***************
Extracted to: /volume1/homebridge/node_modules

Running post-install scripts...
\
|

> @serialport/bindings-cpp@12.0.1 install
> node-gyp-build

|
\

> @stoprocent/bluetooth-hci-socket@1.4.1 install
> node-gyp-build
\
\

> @stoprocent/noble@1.15.1 install
> node-gyp-build
\
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
gyp ERR! stack at async loadConfigGypi (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
gyp ERR! stack at async build (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 4.4.302+
gyp ERR! command "/volume1/@appstore/Node.js_v20/usr/local/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@stoprocent/noble
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok
\
npm error code 1
\
npm error path /volume1/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@stoprocent/noble
\
npm error command failed
\
npm error command sh -c node-gyp-build
\
npm error A complete log of this run can be found in: /var/packages/homebridge/home/.npm/_logs/2024-10-17T01_00_33_651Z-debug-0.log
\
Failed to rebuild.
Restoring previous version...
Restore Complete. Installation failed.

Bundled install / update could not complete. Trying regular install / update using npm.
USER: homebridge
DIR: /volume1/homebridge
CMD: npm install --save @switchbot/homebridge-switchbot@4.0.0
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-

> @serialport/bindings-cpp@12.0.1 install
> node-gyp-build

-
\

> @stoprocent/bluetooth-hci-socket@1.4.1 install
> node-gyp-build
\
\

> @stoprocent/noble@1.15.1 install
> node-gyp-build

\
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
gyp ERR! stack at async loadConfigGypi (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
gyp ERR! stack at async build (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 4.4.302+
gyp ERR! command "/volume1/@appstore/Node.js_v20/usr/local/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@stoprocent/noble
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok
\
|
/
npm error code 1
/npm error path /volume1/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@stoprocent/noble
/npm error command failed
/
npm error command sh -c node-gyp-build
/
npm error A complete log of this run can be found in: /var/packages/homebridge/home/.npm/_logs/2024-10-17T01_00_36_544Z-debug-0.log
/


Error: Operation failed with code 1.

You can download this log file for future reference.

See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "XXX",
        "secret": "XXX",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "XXXXXXXXE9C4",
                "configDeviceName": "Bedroom Curtains",
                "hide_device": false,
                "configDeviceType": "Curtain",
                "connectionType": "OpenAPI",
                "curtain": {
                    "setOpenMode": "1",
                    "setCloseMode": "0"
                },
                "external": false,
                "logging": "standard"
            }
        ]
    },
    "platform": "SwitchBot",
    "_bridge": {
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX
    }
}
```

### Device & Model

Homebridge running on Synology Synology 

### Node.js Version

20.9.0

### NPM Version

10.8.2

### Homebridge Version

1.8.4

### Homebridge SwitchBot Plugin Version

3.8.2 -> 4.0.0

### Homebridge Config UI X Plugin Version

4.61.0

### Operating System

Synology DSM 7.2.1

**Comment by MilanWCC** [comment]
Got exact the same error, can not upgrade. I then deleted the old version, but still after trying to install the latest version I couldn't install it. But now I don't have the older version anymore....

So I can re-install version 3.8.3, but cannot upgrade to 4.x.x, because I then get the error below

I am on Synology v 7.2.1 with the hombridge app on v 3.1.2

```
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
gyp ERR! stack at async loadConfigGypi (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
gyp ERR! stack at async build (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 4.4.302+
gyp ERR! command "/volume1/@appstore/Node.js_v20/usr/local/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@stoprocent/noble
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok 
npm error code 1
npm error path /volume1/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@stoprocent/noble
npm error command failed
npm error command sh -c node-gyp-build
npm error A complete log of this run can be found in: /var/packages/homebridge/home/.npm/_logs/2024-11-10T09_35_09_397Z-debug-0.log
```

**Comment by c0ze** [comment]
looks like key problem is make not installed. this is on synology, not sure how to install make there. 

`
gyp ERR! build error
gyp ERR! stack Error: not found: make
`

**Comment by larsbo** [comment]
This should help: https://github.com/homebridge/homebridge-syno-spk/wiki/DSM-7:-Enable-Compiling-Of-Native-Modules
