### ISSUE TITLE
Bug: Continuous logging of This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value

### ISSUE THREAD

**Issue by semih-akbas** [OpenWonderLabs/homebridge-switchbot#1083]
### Describe the Bug

My homebridge generates the following warning message every second. When I go the the provided url https://homebridge.io/w/JtMGR. It says this is slowing down my homebridge and I should inform the plugin developer for this. Disabling logging did not work for the plugin. Please advise on how to stop this warning...

**[21/10/2024, 10:14:03] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 18000000 exceeded maximum of 100000. See https://homebridge.io/w/JtMGR for more info.**

### To Reproduce

It started happening after I installed the Switchbot plugin to my homebridge

### Expected Behavior

switchbot plugin should not generate that frequent warning message or if there is an issue with the sensor it can be fixed.

### Relevant Log Output

```shell
[21/10/2024, 10:14:03] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 18000000 exceeded maximum of 100000. See https://homebridge.io/w/JtMGR for more info.
[21/10/2024, 10:14:03] [@switchbot/homebridge-switchbot] Error: 
    at CurrentAmbientLightLevel.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3016:105)
    at CurrentAmbientLightLevel.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2932:14)
    at CurrentAmbientLightLevel.Characteristic.updateValue (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2333:20)
    at LightSensor.Service.updateCharacteristic (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:804:35)
    at Motion.updateCharacteristic (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/device.ts:420:15)
    at Motion.updateHomeKitCharacteristics (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/motion.ts:355:7)
    at Object.platform.bleEventHandler.<computed> [as d9:76:2a:ec:38:b2] (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/motion.ts:291:13)
[21/10/2024, 10:14:03] [SwitchBot] Motion Sensor: Hareket updateCharacteristic CurrentAmbientLightLevel: 18000000
[21/10/2024, 10:14:03] [SwitchBot] [DEBUG] Motion Sensor: Hareket CurrentAmbientLightLevel context before: 18000000
[21/10/2024, 10:14:03] [SwitchBot] [DEBUG] Motion Sensor: Hareket CurrentAmbientLightLevel context after: 18000000
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "blahblah",
                "secret": "blahblahblah",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "BLE": true,
                "discoverBLE": true,
                "disableLogsforBLE": true,
                "disableLogsforOpenAPI": true,
                "logging": "none"
            },
            "platform": "SwitchBot"
        }
```

### Device and Model

Raspberry Pi4 for Homebridge, Apparently the issue looks on Switchbot Motion Sensor

### Node.js Version

v20.18.0

### NPM Version

v20.18.0

### Homebridge Version

v1.8.4

### Homebridge Switchbot Plugin Version

v4.0.0

### Homebridge Config UI X Plugin Version

v4.62.0

### Operating System

Debian GNU/Linux Bookworm (12)

**Comment by semih-akbas** [comment]
Closing the bugs since changing the battery of the Motion Detector sensor has fixed the problem.

**Comment by semih-akbas** [comment]
Reopened the issue since after replacing the battery after a while logs came back again...
