### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by trolli-ch** [OpenWonderLabs/homebridge-switchbot#1130]
### Describe Your Problem

Update fails Error: Operation failed with code 1.

### Relevant log output

```shell
> @stoprocent/noble@1.15.1 install
> node-gyp-build


gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:119:22)
gyp ERR! stack at async loadConfigGypi (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:78:7)
gyp ERR! stack at async build (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:36:3)
gyp ERR! stack at async run (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 4.4.302+
gyp ERR! command "/volume1/@appstore/Node.js_v20/usr/local/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@stoprocent/noble
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.2.0
gyp ERR! not ok 
npm error code 1
npm error path /volume1/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@stoprocent/noble
npm error command failed
npm error command sh -c node-gyp-build
npm error A complete log of this run can be found in: /var/packages/homebridge/home/.npm/_logs/2024-12-08T16_22_01_490Z-debug-0.log
Failed to rebuild.
Restoring previous version...
Restore Complete. Installation failed.

Bundled install / update could not complete. Trying regular install / update using npm.

USER: homebridge
DIR: /volume1/homebridge
CMD: npm install --save @switchbot/homebridge-switchbot@4.1.5
```

### Screenshots

[@switchbot_homebridge-switchbot-error.log](https://github.com/user-attachments/files/18053131/%40switchbot_homebridge-switchbot-error.log)

### Device & Model

Ds920

### Node.js Version

v20.9.0

### NPM Version

v10.9.0

### Homebridge Version

v1.8.5

### Homebridge SwitchBot Plugin Version

v3.8.3

### Homebridge Config UI X Plugin Version

v.4.64.0

### Operating System

Synology

**Comment by ghost** [comment]
Same here.

**Comment by l1q1d** [comment]
Hi found a workaround. In my case the home bridge is on a docker.
I went to the home assistant web interface-> terminal:
```
rm -r /var/lib/homebridge/node_modules/\@switchbot
npm install -g @switchbot/homebridge-switchbot
ln -s /opt/homebridge/lib/node_modules/\@switchbot /var/lib/homebridge/node_modules/\@switchbot
```
restart home assistant

**Comment by SaschaTrollGeberit** [comment]
this worked for me

https://github.com/OpenWonderLabs/homebridge-switchbot/issues/1078#issuecomment-2564828872
