### ISSUE TITLE
Bug: TypeError when running 1.3.1-beta.5

### ISSUE THREAD

**Issue by stigyule** [OpenWonderLabs/homebridge-switchbot#141]
### Describe The Bug

TypeErrors in log when trying to run 1.3.1-beta.5, these prevent the plug-in from running.

### To Reproduce

Use the UI to install 1.3.1-beta.5 as a ‘previous version’ then restart Homebridge

### Expected behavior

The plug-in to run without error.

### Relevant log output

```shell
[12/12/2021, 07:03:25] Homebridge v1.3.8 (HAP v0.9.7) (Homebridge 24BF) is running on port 51763.
[12/12/2021, 07:03:26] [SwitchBot] Total SwitchBot Devices Found: 8
[12/12/2021, 07:03:26] [SwitchBot] Restoring existing accessory from cache: Outside Lights DeviceID: C7**********
[12/12/2021, 07:03:26] [SwitchBot] Restoring existing accessory from cache: Data centre meter DeviceID: E6**********
[12/12/2021, 07:03:26] [SwitchBot] Restoring existing accessory from cache: Main bedroom meter DeviceID: E9**********
[12/12/2021, 07:03:26] [SwitchBot] Restoring existing accessory from cache: Data Centre Light DeviceID: EA**********
[12/12/2021, 07:03:26] [SwitchBot] Restoring existing accessory from cache: Landing Dehumidifier DeviceID: EC**********
[12/12/2021, 07:03:26] [SwitchBot] Restoring existing accessory from cache: Data Centre Motion Sensor DeviceID: F4**********
[12/12/2021, 07:03:26] [SwitchBot] Total IR Devices Found: 1
[12/12/2021, 07:03:26] [SwitchBot] Restoring existing accessory from cache: Aircon DeviceID: 02-********
[12/12/2021, 07:03:26] [SwitchBot] Bot: Outside Lights Displaying as Switch
[12/12/2021, 07:03:26] [SwitchBot] Bot: Data Centre Light Displaying as Switch
[12/12/2021, 07:03:26] [SwitchBot] Bot: Landing Dehumidifier Displaying as Switch
[12/12/2021, 07:03:27] TypeError: Cannot read properties of undefined (reading 'body')
    at Bot.openAPIparseStatus (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:201:31)
    at Bot.parseStatus (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:169:18)
    at new Bot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:64:10)
    at SwitchBotPlatform.createBot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:487:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[12/12/2021, 07:03:27] TypeError: Cannot read properties of undefined (reading 'body')
    at Bot.openAPIparseStatus (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:201:31)
    at Bot.parseStatus (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:169:18)
    at new Bot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:64:10)
    at SwitchBotPlatform.createBot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:487:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[12/12/2021, 07:03:27] Got SIGTERM, shutting down Homebridge...
```

### Config for homebridge-switchbot

```shell
{
    "bridge": {
        "name": "Homebridge 24BF",
        "username": "0E:D7:27:82:24:BF",
        "port": 51763,
        "pin": "*******"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                ,
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "********”,
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "********",
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "********",
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    }
                ],
                "irdevices": [
                    {
                        "deviceId": "********",
                        "configRemoteType": "Air Conditioner"
                    }
                ]
            },
            "platform": "SwitchBot"
        },
        {
            "options": {
                "username": "********”,
                "password": "********",
                "accessId": "********”,
                "accessKey": "********",
                "lang": "en",
                "projectType": "2",
                "appSchema": "smartlife",
                "countryCode": 44,
                "debug": false
            },
            "name": "TuyaPlatform",
            "platform": "TuyaPlatform"
        },
        {
            "refreshToken”: “********”
            "platform": "Ring"
        }
    ]
}
```

### Device & Model

SwitchBot V4.8

### Node.js Version

16.3.1

### NPM Version

V8.1.2

### Homebridge Version

V1.3.8

### Homebridge Switchbot Plugin Version

V1.3.1-beta.5

### Homebridge Config UI X Plugin Version

V4.41.4

### Operating System

Homebridge Raspbian 1.0.27

**Comment by donavanbecker** [comment]
Pushed out beta 7, should take care of this.

**Comment by stigyule** [comment]
I installed beta 9 which was the one available and it is working properly
now.

Thank you for the updates.

Regards,

Graham Adams
