### ISSUE TITLE
Support Request: Bot: wasn't able to establish BLE Connection, ending in endless loop

### ISSUE THREAD

**Issue by Bortinio** [OpenWonderLabs/homebridge-switchbot#221]
### Describe Your Problem

Bot: wasn't able to establish BLE Connection, ending in endless loop

Hi,

Please support me to get my configuration running. I am trying to connect a "Bot" via BLE but it seems the connection cannot be established. See the attached logs for the resulting error. The homebridge keeps on restarting until I e.g. change the "ble" to false. Though I don't have a HUB present, hence I planned to use the BLE connection.

### Relevant log output

```shell
[24.1.2022, 19:23:05] [Config] Initializing config platform...
[24.1.2022, 19:23:05] [Config] Running in Service Mode
[24.1.2022, 19:23:09] [SwitchBot] Initializing SwitchBot platform...
[24.1.2022, 19:23:09] [SwitchBot] Using Config Logging: debug
[24.1.2022, 19:23:09] [SwitchBot] [DEBUG] Finished initializing platform:
[24.1.2022, 19:23:09] [SwitchBot] Platform Config: {"logging":"debug"}
[24.1.2022, 19:23:09] [SwitchBot] Using Default Push Rate.
[24.1.2022, 19:23:09] [SwitchBot] [DEBUG] Using Default Refresh Rate (2 minutes).
[24.1.2022, 19:23:09] [SwitchBot] [DEBUG] Config OK
[24.1.2022, 19:23:09] [SwitchBot] Loading accessory from cache: Bot88
[24.1.2022, 19:23:09] [SwitchBot] [DEBUG] Executed didFinishLaunching callback
[24.1.2022, 19:23:10] [SwitchBot] deviceListInfoStatus: {"statusCode":100,"body":{"deviceList":[{"deviceId":"<myDeviceID>","deviceName":"Bot88","deviceType":"Bot","enableCloudService":false,"hubDeviceId":"000000000000"}],"infraredRemoteList":[]},"message":"success"}
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] {"statusCode":100,"body":{"deviceList":[{"deviceId":"<myDeviceID>","deviceName":"Bot88","deviceType":"Bot","enableCloudService":false,"hubDeviceId":"000000000000"}],"infraredRemoteList":[]},"message":"success"}
[24.1.2022, 19:23:10] [SwitchBot] Total SwitchBot Devices Found: 1
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] SwitchBot Device Config Set: [{"deviceId":"<myDeviceID>","configDeviceName":"Bot88","configDeviceType":"Bot","ble":true,"bot":{"mode":"press","deviceType":"switch"}}]
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] SwitchBot Devices: [{"deviceId":"<myDeviceID>","configDeviceName":"Bot88","configDeviceType":"Bot","ble":true,"bot":{"mode":"press","deviceType":"switch"},"deviceName":"Bot88","deviceType":"Bot","enableCloudService":false,"hubDeviceId":"000000000000"}]
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Discovered Bot: <myDeviceID>
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Device: Bot88 BLE Connection Enabled
[24.1.2022, 19:23:10] [SwitchBot] Restoring existing accessory from cache: Bot88 DeviceID: <myDeviceID>
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] "press"
[24.1.2022, 19:23:10] [SwitchBot] Total IR Devices Found: 0
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] IR Device Config Not Set: undefined
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot: Bot88 Using Platform Config Logging: debug
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot: Bot88 Using Default scanDuration: 1
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot: Bot88 Using Platform Config refreshRate: 120
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot: Bot88 Using Bot Mode: press
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot: Bot88 Allowing Push Changes: false
[24.1.2022, 19:23:10] [SwitchBot] Bot: Bot88 Config: {"mode":"press","deviceType":"switch","ble":true}
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot: Bot88 BLE refreshStatus
[24.1.2022, 19:23:10] [SwitchBot] Was 'node-switchbot' found: false
[24.1.2022, 19:23:10] [SwitchBot] Bot: Bot88 Displaying as Switch
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot: Bot88 Add Battery Service
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot: Bot88 updateCharacteristic On: false
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot: Bot88 updateCharacteristic BatteryLevel: 100
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot: Bot88 updateCharacteristic StatusLowBattery: 0
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Bot uuid: <myDeviceID>-Bot, (<myUUID>)
[24.1.2022, 19:23:10] [SwitchBot] [DEBUG] Curtain: Bot88 BLE Address: <myDeviceID>
[24.1.2022, 19:23:10] [SwitchBot] Bot: Bot88 wasn't able to establish BLE Connection: false
[24.1.2022, 19:23:10] TypeError: switchbot.startScan is not a function
    at Bot.BLERefreshStatus (/usr/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:464:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Bot.refreshStatus (/usr/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:444:7)
[24.1.2022, 19:23:10] Got SIGTERM, shutting down Homebridge...
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "<mytoken>",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "<myDeviceID>",
                        "configDeviceName": "Bot88",
                        "configDeviceType": "Bot",
                        "ble": true,
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    }
                ],
                "logging": "debug"
            },
            "platform": "SwitchBot"
}
```

### Device & Model

SwitchBot Bot - firmware v4.9

### Node.js Version

v16.13.2

### NPM Version

v8.1.2

### Homebridge Version

v1.4.0

### Homebridge SwitchBot Plugin Version

v1.10.0

### Homebridge Config UI X Plugin Version

v4.42.0

### Operating System

Raspian

**Comment by stripedew** [comment]
Got the exact same issue here - was working fine for weeks, then the new update broke it. It somehow managed to completely brick my entire Homebridge installation and I had to delete and reinstall from backup.

**Comment by Bortinio** [comment]
Checking the code and the dependencies I understood that node-switchbot needs to be installed manually. Once I did that, the endless loop issue was solved for me and homebridge is running at least. However, the connection issue still persist:

[25.1.2022, 01:56:58] [SwitchBot] Bot: Bot88 wasn't able to establish BLE Connection
[25.1.2022, 01:56:58] [SwitchBot] Bot: Bot88 Using OpenAPI Connection
[25.1.2022, 01:56:59] [SwitchBot] [DEBUG] Bot: Bot88 OpenAPI parseStatus
[25.1.2022, 01:56:59] [SwitchBot] [DEBUG] Bot: Bot88 On: false
[25.1.2022, 01:56:59] [SwitchBot] [DEBUG] Bot: Bot88 updateCharacteristic On: false
[25.1.2022, 01:56:59] [SwitchBot] [DEBUG] Bot: Bot88 updateCharacteristic BatteryLevel: 100
[25.1.2022, 01:56:59] [SwitchBot] [DEBUG] Bot: Bot88 updateCharacteristic StatusLowBattery: 0
[25.1.2022, 01:57:33] [SwitchBot] [DEBUG] Bot: Bot88 On: true
[25.1.2022, 01:57:33] [SwitchBot] [DEBUG] Bot: Bot88 BLE pushChanges On: true OnCached: false
[25.1.2022, 01:57:33] [SwitchBot] [DEBUG] Bot: Bot88 BLE pushChanges
[25.1.2022, 01:57:33] [SwitchBot] [DEBUG] Curtain: Bot88 BLE Address: <myDeviceID>
[25.1.2022, 01:57:33] [SwitchBot] [DEBUG] Bot: Bot88 Bot Mode: press
[25.1.2022, 01:57:38] [SwitchBot] [DEBUG] Bot: Bot88 BLE refreshStatus
[25.1.2022, 01:57:38] [SwitchBot] [DEBUG] Curtain: Bot88 BLE Address: <myDeviceID>
[25.1.2022, 01:57:38] [SwitchBot] Bot: Bot88 On: true
[25.1.2022, 01:57:38] [SwitchBot] Bot: Bot88 failed pushChanges with BLE Connection
[25.1.2022, 01:57:38] [SwitchBot] Bot: Bot88 failed pushChanges with BLE Connection, Error Message: "Cannot read properties of undefined (reading 'press')"

**Comment by donavanbecker** [comment]
How did you install node-SwitchBot?

did you look at the [prerequisites](https://github.com/abandonware/noble#prerequisites) for noble?

**Comment by Bortinio** [comment]
I followed the instructions as written by you on node-switchbot#installation and yes I believe that I have exercised the steps/prerequisites correctly for noble installation too. Still no luck.

**Comment by donavanbecker** [comment]
@Bortinio Node-SwitchBot needs to be installed with the plugin. So you can't just manually install it. Try reinstall homebridge-switchbot, after making sure you have went through all the prerequisites.

If BLE still doesn't work, then I could be something with your pi. Which version is your Pi?

**Comment by Bortinio** [comment]
@donavanbecker ok, I removed the plugin Node-SwitchBot and reinstalled homebridge-switchbot. The issue is still there though:

[25.1.2022, 12:17:49] [SwitchBot] Bot: Bot88 wasn't able to establish BLE Connection
[25.1.2022, 12:17:49] [SwitchBot] Bot: Bot88 Using OpenAPI Connection

I am running a PI3+ with 4.19.66-v7+.

**Comment by donavanbecker** [comment]
Did you see it fail to install node-SwitchBot when installing homebridge-SwitchBot?

Are you install with Homebridge UI? Or Terminal?

**Comment by Bortinio** [comment]
I installed it via Terminal, no issues or failures during installation:

sudo npm -g install @switchbot/homebridge-switchbot
added 70 packages, and audited 71 packages in 1m
6 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities

Seems that node-switchbot was installed, because when it was not, if saw the following entry in the log file:
[25.1.2022, 12:14:24] [SwitchBot] Was 'node-switchbot' found: false

**Comment by donavanbecker** [comment]
@Bortinio Then your raspberryPI for some reason isn't finding your Bot. You could try pushing up the scanDuration. By setting that in the SwitchBot device settings. Try like 10, then you could lower.

**Comment by Bortinio** [comment]
@donavanbecker thank for your ideas here, but also increasing the scanDuration was not successful on my setup. However, I am now thinking to rather put a Switchbot hub in between in order to get a reliable installation and also to expose the bot to Alexa. So I from my perspective this ticket can be closed as being an unresolved mysterious configuration issue...

Thanks!

**Comment by donavanbecker** [comment]
Sorry unfortunately if noble can't find the device then it don't work.

**Comment by stripedew** [comment]
I still have the issue as well - I tried reinstalling, changing various settings, nothing works. Rolling back to v1.9.0 makes it work flawlessly, and then upgrading to v1.10.0 completely breaks it.

**Comment by nmcc1212** [comment]
@Bortinio i think i know what your issue may be
to confirm run `sudo bluetoothctl` on your pi and then try `power on` in the prompt if you get `Changing power on succeeded` then your problem is different, but if you get `No default controller available` i can help

**Comment by Bortinio** [comment]
@nmcc1212 thanks for the hint here, but in the meantime I moved to a Switchbot hub, so I don't have an issue anymore.

**Comment by danielhammerl** [comment]
I had the same problem and as stupid as it sounds but the reason was the limited bluetooth range, i put the raspberry pi closer to the switchbots
