### ISSUE TITLE
Bug: Plugin fails install on new homebridge install.

### ISSUE THREAD

**Issue by PandaUnit-TWL** [OpenWonderLabs/homebridge-switchbot#412]
### Describe The Bug

Plugin fails install on new homebridge install after backup. 

### To Reproduce

Attempt to install plugin after restore from backup. Backup has/had verified Govee, switchbot, and wled plugins. Both Govee and switchbot plugins did not install despite the restore going through each plugin install process automatically. Attempted normal gui install from plugin tab only worked for Govee.

### Expected behavior

Switchbot plugin intalling succesfully

### Relevant log output

```shell
911 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/node-addon-api Completed in 165759ms
912 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/@mapbox/node-pre-gyp Completed in 166597ms
913 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/semver Completed in 167032ms
914 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/nan Completed in 169576ms
915 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/uuid Completed in 169669ms
916 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/axios Completed in 170417ms
917 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/mqtt Completed in 170777ms
918 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/google-auth-library Completed in 171582ms
919 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble Completed in 172590ms
920 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/js-sdsl Completed in 173199ms
921 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/node-forge Completed in 176579ms
922 timing reifyNode:node_modules/@switchbot/homebridge-switchbot Completed in 184128ms
923 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/usb Completed in 193358ms
924 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/rxjs Completed in 243619ms
925 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/googleapis Completed in 310836ms
926 timing reify:unpack Completed in 311367ms
927 timing reify:rollback:createSparse Completed in 27316ms
928 timing reify:rollback:retireShallow Completed in 46ms
929 timing command:install Completed in 426784ms
930 verbose stack Error: process terminated
930 verbose stack     at /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:198:39
930 verbose stack     at process.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
930 verbose stack     at process.emit (node:events:539:35)
931 verbose cwd /var/lib/homebridge
932 verbose Linux 5.15.32+
933 verbose node v16.15.1
934 verbose npm  v8.11.0
935 error process terminated
936 error signal SIGTERM
937 verbose exit 1
938 timing npm Completed in 430266ms
939 verbose unfinished npm timer reify 1656362609776
940 verbose code 1
941 error A complete log of this run can be found in:
941 error     /home/pi/.npm/_logs/2022-06-27T20_43_26_443Z-debug-0.log
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "#######################################################",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "#############",
                        "configDeviceName": "SwitchBot Plug 1",
                        "offline": true,
                        "configDeviceType": "Plug Mini (US)",
                        "logging": "none"
                    }
                ]
            },
            "platform": "SwitchBot"
        }
    ]
}
```

### Screenshots

USER: pi
DIR: /var/lib/homebridge
CMD: npm install --save @switchbot/homebridge-switchbot@latest

npm ERR! process terminated
npm ERR! signal SIGTERM

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-06-27T21_10_50_537Z-debug-0.log

Operation failed. Please review log for details.

### Device & Model

Ras-Pi Zero W

### Node.js Version

v16.15.1

### NPM Version

latest

### Homebridge Version

latest

### Homebridge Switchbot Plugin Version

latest

### Homebridge Config UI X Plugin Version

v4.48.1

### Operating System

Ofiical Ras-Pi homebridge install from June 27, 2022

**Comment by donavanbecker** [comment]
looks like a potential python issue since noble uses that.

**Comment by idanyc** [comment]
I have the same issue... can't install any version... 

Pi Zero WH
Node.js v16.17.1
homebridge@1.5.0
└── npm@8.19.2
```
815 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/nan Completed in 90378ms
816 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/mqtt Completed in 91306ms
817 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/google-auth-library Completed in 92771ms
818 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble Completed in 93339ms
819 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/node-forge Completed in 95675ms
820 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/js-sdsl Completed in 97331ms
821 http fetch GET 200 https://registry.npmjs.org/@switchbot/homebridge-switchbot/-/homebridge-switchbot-2.1.0.tgz 106367ms (cache miss)
822 timing reifyNode:node_modules/@switchbot/homebridge-switchbot Completed in 110384ms
823 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/usb Completed in 125058ms
824 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/rxjs Completed in 170651ms
825 timing reifyNode:node_modules/@switchbot/homebridge-switchbot/node_modules/googleapis Completed in 221529ms
826 timing reify:unpack Completed in 221862ms
827 timing reify:rollback:createSparse Completed in 23469ms
828 timing reify:rollback:retireShallow Completed in 2ms
829 timing command:install Completed in 331567ms
830 verbose stack Error: process terminated
830 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:199:39
830 verbose stack     at process.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:53:5)
830 verbose stack     at process.emit (node:events:525:35)
831 verbose cwd /usr/local
832 verbose Linux 5.10.63+
833 verbose node v16.17.1
834 verbose npm  v8.19.2
835 error process terminated
836 error signal SIGTERM
837 verbose exit 1
838 timing npm Completed in 335103ms
839 verbose unfinished npm timer reify 1665735564421
840 verbose code 1
841 error A complete log of this run can be found in:
841 error     /home/pi/.npm/_logs/2022-10-14T08_19_21_051Z-debug-0.log
```

Config:
```
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "XXXX",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "XXXX",
                        "configDeviceName": "Bathroom",
                        "configDeviceType": "Bot",
                        "ble": false,
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch",
                            "allowPush": true,
                            "doublePress": 1,
                            "maxRetry": 1
                        },
                        "logging": "standard"
                    },
                    {
                        "deviceId": "XXXX",
                        "configDeviceName": "Curtain",
                        "configDeviceType": "Curtain",
                        "ble": false,
                        "curtain": {
                            "hide_lightsensor": true
                        },
                        "refreshRate": 360,
                        "logging": "standard"
                    }
                ],
                "irdevices": [
                    {
                        "logging": "standard"
                    }
                ],
                "logging": "standard"
            },
            "platform": "SwitchBot"
        },

```

**Comment by idanyc** [comment]
managed to install from terminal with 
sudo -E -n npm install -g @switchbot/homebridge-switchbot@latest

got a warn i need node.js 16.18.0 but it succeeded anyways
