### ISSUE TITLE
Bug: TypeError: Cannot read properties of undefined (reading 'setCharacteristic')

### ISSUE THREAD

**Issue by chinedu40** [OpenWonderLabs/homebridge-switchbot#610]
### Describe The Bug

Plugin crashes up starting. 

### To Reproduce

Install v2.3 and have a TV IR device. 

### Expected behavior

For the plugin to run

### Relevant log output

```shell
12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] IR Devices: [{"deviceId":"02-202104141624-85521372","configDeviceName":"Meico Fan","hide_device":true,"deviceName":"Meico Fan ","remoteType":"DIY Fan","hubDeviceId":"C33485982EF2"},{"deviceId":"02-202111282017-48542121","deviceName":"Sony Soundbar","remoteType":"Speaker","hubDeviceId":"C33485982EF2"},{"deviceId":"02-202112132224-68220013","deviceName":"Samsung Projector","remoteType":"TV","hubDeviceId":"C33485982EF2"},{"deviceId":"02-202211100059-63868280","configDeviceName":"Sony 1","hide_device":true,"configRemoteType":"DIY TV","connectionType":"OpenAPI","deviceName":"Sony TV","remoteType":"DIY TV","hubDeviceId":"C33485982EF2"},{"deviceId":"02-202211102320-43055670","configDeviceName":"Sony TV","hide_device":true,"configRemoteType":"DIY TV","connectionType":"OpenAPI","deviceName":"Sony OLED TV","remoteType":"TV","hubDeviceId":"C33485982EF2"}]
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Discovered DIY Fan: 02-202104141624-85521372
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device not registered: Meico Fan  DIY Fan DeviceID: 02-202104141624-85521372
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Discovered Speaker: 02-202111282017-48542121
[12/9/2022, 2:31:06 PM] [SwitchBot] Speaker: Sony Soundbar Using Debug Mode Logging: debugMode
[12/9/2022, 2:31:06 PM] [SwitchBot] Speaker: Sony Soundbar Config: {"connectionType":"OpenAPI","external":true}
[12/9/2022, 2:31:06 PM] [SwitchBot] Speaker: Sony Soundbar accessory.context.FirmwareRevision: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Speaker: Sony Soundbar device.firmware: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Speaker: Sony Soundbar this.platform.version: 2.1.1
[12/9/2022, 2:31:06 PM] [SwitchBot] Speaker: Sony Soundbar accessory.context.FirmwareRevision: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Speaker: Sony Soundbar device.firmware: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Speaker: Sony Soundbar this.platform.version: 2.1.1
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Discovered TV: 02-202112132224-68220013
[12/9/2022, 2:31:06 PM] [SwitchBot] TV: Samsung Projector Using Debug Mode Logging: debugMode
[12/9/2022, 2:31:06 PM] [SwitchBot] TV: Samsung Projector Config: {"connectionType":"OpenAPI","external":true}
[12/9/2022, 2:31:06 PM] [SwitchBot] TV: Samsung Projector accessory.context.FirmwareRevision: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] TV: Samsung Projector device.firmware: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] TV: Samsung Projector this.platform.version: 2.1.1
[12/9/2022, 2:31:06 PM] [SwitchBot] TV: Samsung Projector accessory.context.FirmwareRevision: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] TV: Samsung Projector device.firmware: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] TV: Samsung Projector this.platform.version: 2.1.1
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Discovered DIY TV: 02-202211100059-63868280
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device not registered: Sony TV DIY TV DeviceID: 02-202211100059-63868280
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Discovered TV: 02-202211102320-43055670
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device not registered: Sony OLED TV TV DeviceID: 02-202211102320-43055670
[12/9/2022, 2:31:06 PM] [SwitchBot] Total IR Devices Found: 5
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Bedroom Light Strip registerDevice: true
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Bedroom Light Strip connectionType: OpenAPI, will display in HomeKit
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] deviceName: Living Room Curtain Right deviceId: C71D33F68995, curtainDevicesIds: D01A2D8240C6,C71D33F68995, master: false, group: true, disable_group: undefined, connectionType: OpenAPI
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] deviceName: Living Room Curtain Right [Curtain Config] disable_group: undefined, device.master: false, device.group: true
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Living Room Curtain Right registerCurtains: false, device.connectionType: OpenAPI
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Living Room Curtain hide_device: true, will not display in HomeKit
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: En-Suite registerDevice: true
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: En-Suite connectionType: BLE, will display in HomeKit
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Bedroom Curtain hide_device: true, will not display in HomeKit
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Back Gate hide_device: true, will not display in HomeKit
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Kitchen BLE hide_device: true, will not display in HomeKit
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] deviceName: Curtain B6 deviceId: F30A1750C8B6, curtainDevicesIds: E2764161B173,F30A1750C8B6, master: false, group: true, disable_group: undefined, connectionType: OpenAPI
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] deviceName: Curtain B6 [Curtain Config] disable_group: undefined, device.master: false, device.group: true
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Curtain B6 registerCurtains: false, device.connectionType: OpenAPI
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Living Room Curtain Right Curtain registerDevice: false
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Living Room Curtain Right connectionType: OpenAPI, will display in HomeKit
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Curtain B6 Curtain registerDevice: false
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device: Curtain B6 connectionType: OpenAPI, will display in HomeKit
[12/9/2022, 2:31:06 PM] [SwitchBot] Restoring existing accessory from cache: Bedroom Light Strip DeviceID: A0764E341C5A
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device not registered: Living Room Curtain Curtain DeviceID: D01A2D8240C6
[12/9/2022, 2:31:06 PM] [SwitchBot] Restoring existing accessory from cache: En-Suite DeviceID: E12B5967C255
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device not registered: Bedroom Curtain Curtain DeviceID: E2764161B173
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device not registered: Back Gate Smart Lock DeviceID: E5DA01EB5BF1
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device not registered: Kitchen BLE Smart Lock DeviceID: EC161263A41F
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip Using Debug Mode Logging: debugMode
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip Using Platform Config refreshRate: 120
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip Config: {"connectionType":"OpenAPI"}
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip openAPIRefreshStatus
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip sign: TEERN5iZv9ckkzBpZrJcx9edbZSguMPV80JL7cWx88A=
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip accessory.context.FirmwareRevision: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip device.firmware: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip this.platform.version: 2.1.1
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip accessory.context.FirmwareRevision: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip device.firmware: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip this.platform.version: 2.1.1
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip adaptiveLightingShift: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip adaptiveLighting: true, adaptiveLightingShift: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip updateCharacteristic On: false
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip updateCharacteristic Brightness: 0
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip updateCharacteristic ColorTemperature: 140
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip updateCharacteristic Hue: 0
[12/9/2022, 2:31:06 PM] [SwitchBot] Strip Light: Bedroom Light Strip updateCharacteristic Saturation: 0
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Strip Light uuid: A0764E341C5A-Strip Light, (fba16b12-00ee-4564-9e6c-aac604553b8f)
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device not registered: Living Room Curtain Right Curtain DeviceID: C71D33F68995
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite Using Debug Mode Logging: debugMode
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite Using Default scanDuration: 1
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite Using Device Config refreshRate: 30
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite Config: {"connectionType":"BLE","refreshRate":30}
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite BLERefreshStatus
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite accessory.context.FirmwareRevision: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite device.firmware: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite this.platform.version: 2.1.1
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite accessory.context.FirmwareRevision: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite device.firmware: undefined
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite this.platform.version: 2.1.1
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite Add Temperature Sensor Service
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite Add Humidity Sensor Service
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite Add Battery Service
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite updateCharacteristic CurrentRelativeHumidity: 0
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite updateCharacteristic CurrentTemperature: 0
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite updateCharacteristic BatteryLevel: 100
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite updateCharacteristic StatusLowBattery: 0
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Meter uuid: E12B5967C255-Meter, (603bd643-761b-4641-bd35-ec6c51471141)
[12/9/2022, 2:31:06 PM] [SwitchBot] [DEBUG] Device not registered: Curtain B6 Curtain DeviceID: F30A1750C8B6
[12/9/2022, 2:31:06 PM] [SwitchBot] Meter: En-Suite BLE Address: e1:2b:59:67:c2:55

/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/irdevice/tv.ts:53
   
                   ^
TypeError: Cannot read properties of undefined (reading 'setCharacteristic')
    at new TV (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/irdevice/tv.ts:53:20)
    at SwitchBotPlatform.createTV (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:1331:7)
    at SwitchBotPlatform.createIRDevice (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:499:16)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:363:24)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[12/9/2022, 2:31:06 PM] [SwitchBot] Child bridge process ended
[12/9/2022, 2:31:06 PM] [SwitchBot] Process Ended. Code: 1, Signal: null
[12/9/2022, 2:31:13 PM] [SwitchBot] Restarting Process...
[12/9/2022, 2:31:14 PM] [SwitchBot] Launched child bridge with PID 6733
[12/9/2022, 2:31:17 PM] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
```

### Config for homebridge-switchbot

```shell
{
    "bridge": {
        "name": "Homebridge FD17",
        "username": "0E:25:E6:44:FD:17",
        "port": 51913,
        "pin": "898-43-144",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "token": "XXXX",
                "secret": "XXXX",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "E5DA01EB5BF1",
                        "configDeviceName": "Back Gate",
                        "hide_device": true,
                        "configDeviceType": "Smart Lock",
                        "connectionType": "BLE",
                        "refreshRate": 30,
                        "external": false
                    },
                    {
                        "deviceId": "EC161263A41F",
                        "configDeviceName": "Kitchen BLE",
                        "hide_device": true,
                        "configDeviceType": "Smart Lock",
                        "connectionType": "BLE",
                        "scanDuration": 30
                    },
                    {
                        "deviceId": "E2764161B173",
                        "configDeviceName": "Bedroom Curtain",
                        "hide_device": true
                    },
                    {
                        "deviceId": "D01A2D8240C6",
                        "configDeviceName": "Living Room Curtain",
                        "hide_device": true
                    },
                    {
                        "deviceId": "A0764E34E47A",
                        "configDeviceName": "Study Light Strip",
                        "hide_device": true
                    },
                    {
                        "deviceId": "E12B5967C255",
                        "configDeviceName": "En-Suite",
                        "configDeviceType": "Meter",
                        "connectionType": "BLE",
                        "refreshRate": 30
                    }
                ],
                "irdevices": [
                    {
                        "deviceId": "02-202104141624-85521372",
                        "configDeviceName": "Meico Fan",
                        "hide_device": true
                    },
                    {
                        "deviceId": "02-202211102320-43055670",
                        "configDeviceName": "Sony TV",
                        "hide_device": true,
                        "configRemoteType": "DIY TV",
                        "connectionType": "OpenAPI"
                    },
                    {
                        "deviceId": "02-202211100059-63868280",
                        "configDeviceName": "Sony 1",
                        "hide_device": true,
                        "configRemoteType": "DIY TV",
                        "connectionType": "OpenAPI"
                    }
                ],
                "logging": "debug"
            },
            "_bridge": {
                "username": "0E:FC:61:FF:0C:E9",
                "port": 31247
            },
            "platform": "SwitchBot"
        }
    ],
    "disabledPlugins": []
}
```

### Device & Model

Raspberry Pi 4

### Node.js Version

16.8.2

### NPM Version

v8.19.2

### Homebridge Version

v1.6

### Homebridge Switchbot Plugin Version

2.3

### Operating System

Raspbian

**Comment by krukje** [comment]
I have this too. Have to disable switchbot in HomeBridge otherwise it crashes on startup. This is the log message:

```
[10/12/2022, 13:57:22] TypeError: Cannot read properties of undefined (reading 'setCharacteristic')
    at new TV (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/irdevice/tv.ts:53:20)
    at SwitchBotPlatform.createTV (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:1331:7)
    at SwitchBotPlatform.createIRDevice (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:499:16)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:363:24)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

```

**Comment by donavanbecker** [comment]
I will look into this

**Comment by Gordon-Newell** [comment]
Confirmed I have this same issue too.

Removing the TV from the switchbot hub allows homebridge to boot

**Comment by aleksandr-vin** [comment]
Same for Set Top Box and Projector

**Comment by aleksandr-vin** [comment]
I've used Fan type (as only on/off is supported by HomeKit anyway) as a workaround. Now have too many fans in mu home :)

**Comment by Revillaj** [comment]
Im getting this error as well, restarts the startup as a result of the error, 
[11/12/2022, 19:13:43] [SwitchBot] Total IR Devices Found: 3
[11/12/2022, 19:13:43] TypeError: Cannot read properties of undefined (reading 'setCharacteristic')
    at new TV (/usr/lib/node_modules/@switchbot/homebridge-switchbot/src/irdevice/tv.ts:53:20)
    at SwitchBotPlatform.createTV (/usr/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:1331:7)
    at SwitchBotPlatform.createIRDevice (/usr/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:499:16)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:344:26)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)


My homebridge instance is running on a raspberry pi 4, I tried both sudo apt-get upgrade and sudo apt-get update and nothing.

**Comment by donavanbecker** [comment]
v2.3.1 should fix this.

**Comment by chinedu40** [comment]
> v2.3.1 should fix this.

This solved the issue. Thanks
