### ISSUE TITLE
Support Request: I can't update or reinstall Switchbot plugin

### ISSUE THREAD

**Issue by mkizzle2906** [OpenWonderLabs/homebridge-switchbot#728]
### Describe Your Problem

I can't update or reinstall Switchbot plugin. Please help me to update it before closing the topic

### Relevant log output

```shell
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g @switchbot/homebridge-switchbot@2.6.2

(##################) ⠙ reify:googleapis: timing reifyNode:node_modules/@switchbot/home
> @abandonware/bluetooth-hci-socket@0.5.3-10 install
> node-pre-gyp install --fallback-to-build --update-binary

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-10/bluetooth_hci_socket-0.5.3-10-node-v108-linux-arm.tar.gz(##################) ⠼ reify:googleapis: timing reifyNode:node modules/@switchbot/home
make: Entering directory '/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/bluetooth_hci_socket/src/BluetoothHciSocket.o
make: g++: No such file or directory
make: *** [bluetooth_hci_socket.target.mk:111: Release/obj.target/bluetooth_hci_socket/src/BluetoothHciSocket.o] Error 127
make: Leaving directory '/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.10.103-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--update-binary" "--module=/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node" "--module_name=bluetooth_hci_socket" "--module_path=/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd /usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket
gyp ERR! node -v v18.16.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 5.10.103-v7l+ing reifyNode:node_modules/@switchbot/home
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket
node-pre-gyp ERR! node -v v18.16.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)

> @abandonware/noble@1.9.2-20 install
> node-gyp-build

make: Entering directory '/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble/build'
  SOLINK_MODULE(target) Release/obj.target/noble.node
make: g++: No such file or directory
make: *** [noble.target.mk:20: Release/obj.target/noble.node] Error 127
make: Leaving directory '/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble/build'
gyp ERR! build error 
gyp ERR! stack(##################) ⠙ reify:googleapis: timing reifyNode:node_modules/@s Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.10.103-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble
gyp ERR! node -v v18.16.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2023-04-18T02_58_05_843Z-debug-0.log

Operation failed. Please review log for details.
```

### Device & Model

Pi

### Node.js Version

v18.16.0

### NPM Version

v9.5.1

### Homebridge Version

v1.6.0

### Homebridge SwitchBot Plugin Version

v2.6.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
once again, please Look through what they had to do to fix this on #713,. This is not a plugin issue.

**Comment by mkizzle2906** [comment]
> once again, please Look through what they had to do to fix this on #713,. This is not a plugin issue.

I tried all but still can't install that bluetooth-hci-socket & noble packages

**Comment by marvinjoa** [comment]
> > once again, please Look through what they had to do to fix this on #713,. This is not a plugin issue.
> 
> 
> 
> I tried all but still can't install that bluetooth-hci-socket & noble packages

@mkizzle2906 Try this: https://github.com/OpenWonderLabs/homebridge-switchbot/issues/691#issuecomment-1510001817

But also install noble after the Hci socket:

`npm i @abandonware/noble`

**Comment by mkizzle2906** [comment]
> #691 (comment)

I don't have this following folder : /var/lib/homebridge/node_modules/@switchbot
and I can't install neither bluetooth-hci-socket or noble with that command...

**Comment by marvinjoa** [comment]
> > #691 (comment)
> 
> 
> 
> I don't have this following folder : /var/lib/homebridge/node_modules/@switchbot
> 
> and I can't install neither bluetooth-hci-socket or noble with that command...

Look at your error log. Your folder seems to be called '/usr/local/lib/node_modules/@switchbot/'

**Comment by donavanbecker** [comment]
Thanks @marvinjoa! I will add this to a BLE wiki, I have on here that you can reference.

**Comment by donavanbecker** [comment]
@marvinjoa [Bluetooth Issues Wiki](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Bluetooth-Issues#steps-that-may-help-resolve-ble-issues-from-issue-691)

Let me know if you want me to add or remove anything.

**Comment by marvinjoa** [comment]
> @marvinjoa [Bluetooth Issues Wiki](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Bluetooth-Issues#steps-that-may-help-resolve-ble-issues-from-issue-691)
> 
> 
> 
> Let me know if you want me to add or remove anything.

Thanks, this will make it easier for everybody!

But even with this, people that didn't use the HomeBridge image, but installed HomeBridge manually, will get confused when the folders I mentioned don't exit, cause they don't look in their own error logs 😭

**Comment by bwp91** [comment]
i might need this wiki page for govee plugin 😅

**Comment by donavanbecker** [comment]
> Thanks, this will make it easier for everybody!
> 
> But even with this, people that didn't use the HomeBridge image, but installed HomeBridge manually, will get confused when the folders I mentioned don't exit, cause they don't look in their own error logs 😭

We can only help so much...
