### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by tobias11-at** [OpenWonderLabs/homebridge-switchbot#748]
### Describe the Bug

Hello, installation is unfortunably not possible.
Thanks.
Tobias

### To Reproduce

Pressed installation

### Expected Behavior

Installation

### Relevant Log Output

```shell
USER: homebridge
DIR: /volume1/@appdata/homebridge
CMD: npm install -g @switchbot/homebridge-switchbot@2.6.2

[##################] / reify:googleapis: timing reifyNode:node_modules/@switchbot/home
> @abandonware/bluetooth-hci-socket@0.5.3-10 install
> node-pre-gyp install --fallback-to-build --update-binary

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-10/bluetooth_hci_socket-0.5.3-10-node-v93-linux-x64.tar.gz 
gyp ERR! build error - reify:googleapis: timing reifyNode:node_modules/@switchbot/home
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 4.4.180+
gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--update-binary" "--module=/volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node" "--module_name=bluetooth_hci_socket" "--module_path=/volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v8.3.0
gyp ERR! not ok 
node-pre-gyp ERR! build error oogleapis: timing reifyNode:node_modules/@switchbot/home
node-pre-gyp ERR! stack Error: Failed to execute '/volume1/@appstore/homebridge/app/bin/node /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Linux 4.4.180+
node-pre-gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
node-pre-gyp ERR! cwd /volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket
node-pre-gyp ERR! node -v v16.13.2
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok 
Failed to execute '/volume1/@appstore/homebridge/app/bin/node /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)

> @abandonware/noble@1.9.2-20 install
> node-gyp-build

gyp ERR! build error \ reify:googleapis: timing reifyNode:node_modules/@switchbot/home
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 4.4.180+
gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v8.3.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2023-06-05T10_29_27_925Z-debug.log

Operation failed. Please review log for details.
```

### Config for homebridge-switchbot

```shell
config.json
```

### Device and Model

NAS Synology

### Node.js Version

18

### NPM Version

?

### Homebridge Version

1.6.1

### Homebridge Switchbot Plugin Version

2.6.2

### Homebridge Config UI X Plugin Version

4.50.4

### Operating System

Docker

**Comment by donavanbecker** [comment]
Please checkout the [Bluetooth Issues Wiki](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Bluetooth-Issues)
