### ISSUE TITLE
Plugin and/or dependencies disappears

### ISSUE THREAD

**Issue by marvinjoa** [OpenWonderLabs/homebridge-switchbot#752]

**Comment by marvinjoa** [comment]
[@switchbot/homebridge-switchbot] node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at target._send (node:internal/child_process:865:20)
    at target.send (node:internal/child_process:738:19)
    at PluginUiServer.ready (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@homebridge/plugin-ui-utils/dist/server.js:105:17)
    at new PluginUiServer (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/homebridge-ui/server.js:46:10)
    at /var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/homebridge-ui/server.js:50:8
    at Object.<anonymous> (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/homebridge-ui/server.js:50:29)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
Emitted 'error' event on process instance at:
    at node:internal/child_process:869:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v18.16.0
