### ISSUE TITLE
Bug: Bot not working anymore under 1.0.0

### ISSUE THREAD

**Issue by yjeanrenaud** [OpenWonderLabs/homebridge-switchbot#77]
### Describe The Bug

updateCharacteristic failed

### To Reproduce

I added the Bot's device ID to in order to configure it as Press or Switch. The bug crashes the whole homebridge instance. I can only get it working when I hide the Bot device

### Expected behavior

it should work

### Relevant log output

```shell
Bot Bot 5F failed to refresh status, Error Message: "Cannot read properties of undefined (reading 'updateCharacteristic')"
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "SECRET",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "FF0A3A38F35F",
                        "hide_device": true,
                        "deviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "switch": false
                        }
                    }
                ],
                "refreshRate": 30,
                "pushRate": 1
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

SwitchBot Bot

### Node.js Version

v16.13.0

### NPM Version

v8.1.1 

### Homebridge Version

v1.3.6 

### Homebridge Switchbot Plugin Version

1.0.0

### Homebridge Config UI X Plugin Version

v4.41.2 

### Operating System

Debian

**Comment by donavanbecker** [comment]
You have `"hide_device": true,` if you want it to be displayed I. HomeKit you will need to uncheck or make that false.

**Comment by BigKrisch** [comment]
I get the same error message with the bots even though hide_device is set to false.
However, the error only occurs with the bots. The curtains work perfectly.


> {
>                 "deviceId": "DA4CD7E58099",
>                 "hide_device": false,
>                 "deviceType": "Bot",
>                 "ble": false,
>                 "bot": {
>                     "mode": "switch",
>                     "switch": true
>                 }
>             },
>             {
>                 "deviceId": "F2A3DD9D8018",
>                 "hide_device": false,
>                 "deviceType": "Bot",
>                 "ble": false,
>                 "bot": {
>                     "mode": "switch",
>                     "switch": true
>                 }
>             },
>             {
>                 "deviceId": "DDBEE08B89AB",
>                 "hide_device": false,
>                 "deviceType": "Curtain",
>                 "ble": false,
>                 "curtain": {
>                     "disable_group": false,
>                     "refreshRate": 5,
>                     "set_minStep": 1,
>                     "set_min": 0,
>                     "set_max": 100
>                 }
>             },
>             {
>                 "deviceId": "D8577A7DF1FC",
>                 "hide_device": false,
>                 "deviceType": "Curtain",
>                 "ble": false,
>                 "curtain": {
>                     "disable_group": false,
>                     "refreshRate": 5,
>                     "set_minStep": 1,
>                     "set_min": 0,
>                     "set_max": 100
>                 }
>             }



```
[13.11.2021, 22:27:55] [SwitchBot] Child bridge process ended
[13.11.2021, 22:27:55] [SwitchBot] Process Ended. Code: 1, Signal: null
[13.11.2021, 22:28:02] [SwitchBot] Restarting Process...
[13.11.2021, 22:28:03] [SwitchBot] Launched child bridge with PID 29379
[13.11.2021, 22:28:04] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[13.11.2021, 22:28:04] [SwitchBot] Loaded @switchbot/homebridge-switchbot v1.0.0 child bridge successfully
[13.11.2021, 22:28:04] Loaded 4 cached accessories from cachedAccessories.0EA117226B20.
[13.11.2021, 22:28:04] [SwitchBot] Loading accessory from cache: Schlafzimmer Vorhang Rechts
[13.11.2021, 22:28:04] [SwitchBot] Loading accessory from cache: Schlafzimmer Vorhang Links
[13.11.2021, 22:28:04] [SwitchBot] Loading accessory from cache: Arbeitszimmer Drucker
[13.11.2021, 22:28:04] [SwitchBot] Loading accessory from cache: iMac
[13.11.2021, 22:28:04] Homebridge v1.3.6 (HAP v0.9.7) (Homebridge-Switchbot) is running on port 54547.
[13.11.2021, 22:28:05] [SwitchBot] Total SwitchBot Devices Found: 5
[13.11.2021, 22:28:05] [SwitchBot] Restoring existing accessory from cache: Schlafzimmer Vorhang Rechts DeviceID: D8577A7DF1FC
[13.11.2021, 22:28:05] [SwitchBot] Restoring existing accessory from cache: Arbeitszimmer Drucker DeviceID: DA4CD7E58099
[13.11.2021, 22:28:05] [SwitchBot] Restoring existing accessory from cache: Schlafzimmer Vorhang Links DeviceID: DDBEE08B89AB
[13.11.2021, 22:28:05] [SwitchBot] Restoring existing accessory from cache: iMac DeviceID: F2A3DD9D8018
[13.11.2021, 22:28:05] [SwitchBot] Total IR Devices Found: 0
[13.11.2021, 22:28:05] [SwitchBot] Bot Arbeitszimmer Drucker failed to refresh status, Error Message: "Cannot read properties of undefined (reading 'updateCharacteristic')"
[13.11.2021, 22:28:05] [SwitchBot] Bot iMac failed to refresh status, Error Message: "Cannot read properties of undefined (reading 'updateCharacteristic')"

/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:356
    this.service.updateCharacteristic(this.platform.Characteristic.On, e);
                 ^
TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at Bot.apiError (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:356:18)
    at Bot.openAPIRefreshStatus (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:233:12)
    at Bot.refreshStatus (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:168:18)
    at new Bot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:52:10)
    at SwitchBotPlatform.createBot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:440:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[13.11.2021, 22:28:05] [SwitchBot] Child bridge process ended
```

**Comment by yjeanrenaud** [comment]
> 
> 
> You have `"hide_device": true,` if you want it to be displayed I. HomeKit you will need to uncheck or make that false.

yes because otherwise hb crashes.

**Comment by donavanbecker** [comment]
@yjeanrenaud @nyjklein @adamrzanek, can you try Beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.0.1-beta.2/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by adamrzanek** [comment]
@donavanbecker nope still nothing

**Comment by donavanbecker** [comment]
@adamrzanek you have beta2 or higher installed? because bots are working for me both bluetooth and openapi. do you have more logs?

**Comment by adamrzanek** [comment]
Right now I have beta 3

>

**Comment by adamrzanek** [comment]
![Uploading E9EA5E5E-5D77-472C-9A45-E166549A9F40.png…]()

**Comment by adamrzanek** [comment]
![9455FAD9-720B-44D5-B02E-C1CCDE3529F1](https://user-images.githubusercontent.com/65444919/141685822-a9a494e6-1cef-466e-a30c-0d2921751024.png)

**Comment by donavanbecker** [comment]
@adamrzanek from the logs it looks like there are no devices in your SwitchBot account (opentoken), also have you enabled Cloud Service?

**Comment by adamrzanek** [comment]
@donavanbecker I was asking in other threat that I want to use my bot without the hub with rpi only - like I can with other plugin. Don’t know how to enable cloud service without the hub
>

**Comment by nyjklein** [comment]
With Beta 3 I have things working again. I'm not sure if it was purely beta 3 or the changes I made to my config adding this:

                "devices": [
                    {
                        "deviceId": "xxxxxxxxxxxx",
                        "hide_device": false,
                        "deviceType": "Bot",
                        "ble": false,
                        "bot": {
                            "mode": "switch",
                            "switch": true,
                            "deviceType": "outlet"
                        }
                    }

**Comment by adamrzanek** [comment]
@donavanbecker I didn’t know that I had to add the bot to my “switchbot home”. But I can’t enable cloud service because I don’t have hub
![E3003F9B-F318-4012-ABE9-1FD5C0BD3EB6](https://user-images.githubusercontent.com/65444919/141687903-d57e9715-d856-4822-b862-aa8640e898ae.png)

**Comment by ex725** [comment]
how do i use bot without hub.
as in this plugin

https://github.com/ewebdev/homebridge-switchbot-ble#readme


[11/14/2021, 19:59:17] The plugin "homebridge-switchbot" requires Node.js version of ^14.18.1 || ^16.13.0 which does not satisfy the current Node.js version of v12.18.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
[11/14/2021, 19:59:17] ====================
[11/14/2021, 19:59:17] ERROR LOADING PLUGIN @switchbot/homebridge-switchbot:
[11/14/2021, 19:59:17] /usr/local/lib/node_modules/@switchbot/homebridge-switchbot/dist/platform.js:69
            request.headers.Authorization = this.config.credentials?.openToken;
                                                                    ^

SyntaxError: Unexpected token '.'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/index.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
[11/14/2021, 19:59:17] ====================

![image](https://user-images.githubusercontent.com/56446241/141690750-053b5748-5916-4508-a8d7-b163cc9e2d4a.png)

**Comment by ex725** [comment]
how do i use bot without hub
as in this plugin

https://github.com/ewebdev/homebridge-switchbot-ble#readme

**Comment by sshinnawy** [comment]
I am having the same issue. Did anyone find a fix?

**Comment by donavanbecker** [comment]
> I am having the same issue. Did anyone find a fix?

@sshinnawy, Which issue are you referring too?

**Comment by yjeanrenaud** [comment]
> 
> 
> @yjeanrenaud @nyjklein @adamrzanek, can you try Beta:
> 
> [![npm version](https://camo.githubusercontent.com/eee8c1861f5e8f569f48dcda2d018c485d5dbf738934d6e1128569969e60a87e/68747470733a2f2f62616467656e2e6e65742f62616467652f686f6d656272696467652d737769746368626f7440626574612f2533453d312e302e312d626574612e322f6f72616e6765)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)
> 
> [Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

beta 3 does not crash my hb, but I get 
`[14/11/2021, 23:26:32] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"`
even though the token is correct.

**Comment by yjeanrenaud** [comment]
never mind. for some reason, the hub mini was removed from my profile in the Switchhub app and therefore no cloud connection was available anymore. weird

**Comment by yjeanrenaud** [comment]
so to make this clear: the auth issue was not related to beta 3. beta 3 indeed solves the issue with the Bot crashing all the homebridge

**Comment by donavanbecker** [comment]
@yjeanrenaud perfect! I have release v1.0.1

**Comment by donavanbecker** [comment]
> how do i use bot without hub as in this plugin
> 
> [ewebdev/homebridge-switchbot-ble#readme](https://github.com/ewebdev/homebridge-switchbot-ble#readme)

Enable BLE for the device you want to use BLE on.

**Comment by ex725** [comment]
> > how do i use bot without hub as in this plugin
> > [ewebdev/homebridge-switchbot-ble#readme](https://github.com/ewebdev/homebridge-switchbot-ble#readme)
> 
> Enable BLE for the device you want to use BLE on.

i did that but it didn't work

**Comment by donavanbecker** [comment]
> i did that but it didn't work

You will have to open up an issue so I can get more info of your setup.
