### ISSUE TITLE
Bug: Only Temperature is not being retrieved from Switchbot Meter.

### ISSUE THREAD

**Issue by watakushi-info** [OpenWonderLabs/homebridge-switchbot#78]
### Describe The Bug

Only Temperature is not being retrieved from Switchbot Meter.

### To Reproduce

At the Homebridge UI accessory view, You can see that the temperature is displayed as 0.1 C. If you wait a few seconds, the correct number will be displayed, but if you refresh the browser, it will display 0.1 C again.

### Expected behavior

At the Homebridge UI accessory view, the temperature is displayed as 0.1 C. If you wait a few seconds, the correct number will be displayed, but if you refresh the browser, it will display 0.1 C again.

### Relevant log output

```shell
[11/14/2021, 4:04:16 AM] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[11/14/2021, 4:04:16 AM] [@switchbot/homebridge-switchbot] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1967:16)
    at CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1492:24)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11/14/2021, 4:04:16 AM] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
```

### Config for homebridge-switchbot

```shell
{
    "bridge": {
        "name": "Homebridge 7312",
        "username": "SECRET",
        "port": SECRET,
        "pin": "SECRET"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "SECRET",
                "notice": "Keep your token a secret!"
            },
            "platform": "SwitchBot",
            "_bridge": {
                "username": "SECRET",
                "port": 46530
            }
        }
    ]
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/63475228/141656255-e1d49244-457a-4920-b04a-c6d55e559504.png)

### Device & Model

SWITCHBOT-METERTH-S1

### Node.js Version

v16.13.0

### NPM Version

v8.1.0

### Homebridge Version

v1.3.6

### Homebridge Switchbot Plugin Version

v1.0.0

### Operating System

Docker

**Comment by donavanbecker** [comment]
@watakushi-info, can you try Beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.0.1-beta.3/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

**Comment by watakushi-info** [comment]
Thank you very much for making the fix.
At the Homebridge UI accessory view, the temperature works well.
I believe the fix is probably complete for this issue. Thank you very much.

The error message still shows up, but it may be related to a different problem.
Looking at the messages before the error message, my guess is that the error message might be related to air conditioning.
(The only Switchbot gadget that is related to 'Current Temperature' is the air conditioner, except for the Meter.)

> [11/14/2021, 11:57:14 PM] [SwitchBot] CurrentHeaterCoolerStateGet: 0
> [11/14/2021, 11:57:14 PM] [SwitchBot] onGet: 24
> [11/14/2021, 11:57:14 PM] [SwitchBot] Trigger Get CurrentTemperture
> [11/14/2021, 11:57:14 PM] [SwitchBot] HeatingThresholdTemperatureGet: 24
> [11/14/2021, 11:57:14 PM] [SwitchBot] HeatingThresholdTemperatureGet: 24
> [11/14/2021, 11:57:14 PM] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
> [11/14/2021, 11:57:14 PM] [@switchbot/homebridge-switchbot] Error: 
>     at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
>     at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1967:16)
>     at CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1492:24)
>     at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
>     at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
>     at fulfilled (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by donavanbecker** [comment]
I will keep track of the air conditioner issue on #43.
