### ISSUE TITLE
Bug: `Firmware Revision` Characteristic Errors After Latest NodeJS Update

### ISSUE THREAD

**Issue by iSteve-O** [OpenWonderLabs/homebridge-switchbot#829]
### Describe the Bug

Everything seems to be working fine, I just got the following errors in the log

### To Reproduce

Configure a bot with the latest version of node.

### Expected Behavior

No error.

### Relevant Log Output

```shell
19/09/2023, 23:47:08] [SwitchBot] Total SwitchBot Devices Found: 2
[19/09/2023, 23:47:08] [SwitchBot] Speaker: Soundbar this.platform.version, FirmwareRevision: 2.1.1
[19/09/2023, 23:47:08] [SwitchBot] Speaker: Soundbar setFirmwareRevision: 2.1.1
[19/09/2023, 23:47:08] [SwitchBot] Total IR Devices Found: 1
[19/09/2023, 23:47:08] [SwitchBot] Restoring existing accessory from cache: Coffee Maker DeviceID: XXX
[19/09/2023, 23:47:08] Soundbar EFF0 is running on port 37645.
[19/09/2023, 23:47:08] Please add [Soundbar EFF0] manually in Home app. Setup Code: 502-10-970
[19/09/2023, 23:47:08] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Firmware Revision': Characteristic not in required or optional characteristic section for service Battery. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[19/09/2023, 23:47:08] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Firmware Revision': Characteristic not in required or optional characteristic section for service Switch. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "XXX",
                "secret": "XXX",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "XXX",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    }
                ],
                "irdevices": [
                    {
                        "deviceId": "Soundbar",
                        "configRemoteType": "Speaker",
                        "connectionType": "OpenAPI",
                        "external": true
                    }
                ]
            },
            "_bridge": {
                "username": "0E:B1:4E:29:AD:AA",
                "port": 38561,
                "model": "SwitchBot"
            },
            "platform": "SwitchBot"
        }
```

### Device and Model

hub mini, bot

### Node.js Version

v18.18.0

### NPM Version

v10.1.0

### Homebridge Version

v1.6.1

### Homebridge Switchbot Plugin Version

v2.9.0

### Homebridge Config UI X Plugin Version

v4.50.5

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Wouldn't worry about it.

**Comment by xhi-nico** [comment]
I'm getting the same error and it's causing my Homebridge to go on a reboot loop. Won't start with it.

`[25/09/2023, 12:31:08] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Firmware Revision': Characteristic not in required or optional characteristic section for service Battery. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[25/09/2023, 12:31:08] TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at Lock.updateHomeKitCharacteristics (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/lock.ts:554:36)
    at Lock.openAPIRefreshStatus (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/lock.ts:360:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Lock.refreshStatus (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/lock.ts:265:7)`

I had to go back to 2.8.2.

**Comment by donavanbecker** [comment]
Haven't had much time to look at this. When I do, I will let you know when I have a new beta out for testing.

**Comment by ezerr** [comment]
I have the same problem as @GeorgeeNico but I had to downgrade to 2.8.1. I still get the warnings on 2.8.1 but no boot loop.

**Comment by agentadam-code** [comment]
I have the same issue. Updated and stuck in restart loop. Downgraded to 2.8 and it works fine. I tried other combinations of updates too like downgrading Homebridge UI and Homebridge to other versions but it also broke Homebridge.

I only have Blind Tilts in my setup if that helps.

Just seems something in 2.9 breaks things. Will stay on 2.8 until a fix is implemented.

**Comment by donavanbecker** [comment]
Can you all try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.9.1-beta.4/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

And report back.

**Comment by agentadam-code** [comment]
Works! Well done.

**Comment by donavanbecker** [comment]
> Works! Well done. 

Awesome, I will get a release out soon.

**Comment by donavanbecker** [comment]
v2.9.1 has been released
