### ISSUE TITLE
v3.1.2 leads to endless restart of child bridge. When restarting HomeBridge no plugins are loaded. 

### ISSUE THREAD

**Issue by hansw1204** [OpenWonderLabs/homebridge-switchbot#922]
### Describe the Bug

v3.1.2 created a re-start loop of the plugin.  v3.1.1 is alsod isfunctional (as before). Downgrading to 3.1.0 corrects the problem

### To Reproduce

update to v.3.1.2

### Expected Behavior

functional plugin

### Relevant Log Output

```shell
[2/5/2024, 4:19:23 PM] [SwitchBot] Initializing SwitchBot platform...
[2/5/2024, 4:19:23 PM] [SwitchBot] Initializing child bridge 0E:60:3D:E2:5A:D4
[2/5/2024, 4:19:29 PM] [SwitchBot] Launched child bridge with PID 910
[2/5/2024, 4:19:40 PM] [SwitchBot] Loaded @switchbot/homebridge-switchbot v3.1.0 child bridge successfully
[2/5/2024, 4:19:40 PM] Loaded 2 cached accessories from cachedAccessories.0E603DE25AD4.
Error: listen EADDRINUSE: address already in use :::34884
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at EventedHTTPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:193:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:174:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
[2/5/2024, 4:19:41 PM] [SwitchBot] Child bridge process ended
[2/5/2024, 4:19:41 PM] [SwitchBot] Process Ended. Code: 1, Signal: null
[2/5/2024, 4:19:48 PM] [SwitchBot] Restarting Process...
[2/5/2024, 4:19:48 PM] [SwitchBot] Launched child bridge with PID 1141
[2/5/2024, 4:19:51 PM] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[2/5/2024, 4:19:51 PM] [SwitchBot] Loaded @switchbot/homebridge-switchbot v3.1.0 child bridge successfully
[2/5/2024, 4:19:51 PM] Loaded 2 cached accessories from cachedAccessories.0E603DE25AD4.
Error: listen EADDRINUSE: address already in use :::34884
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at EventedHTTPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:193:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:174:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
[2/5/2024, 4:19:51 PM] [SwitchBot] Child bridge process ended
[2/5/2024, 4:19:51 PM] [SwitchBot] Process Ended. Code: 1, Signal: null
[2/5/2024, 4:19:58 PM] [SwitchBot] Restarting Process...
[2/5/2024, 4:19:59 PM] [SwitchBot] Launched child bridge with PID 1181
[2/5/2024, 4:20:02 PM] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[2/5/2024, 4:20:02 PM] [SwitchBot] Loaded @switchbot/homebridge-switchbot v3.1.0 child bridge successfully
[2/5/2024, 4:20:02 PM] Loaded 2 cached accessories from cachedAccessories.0E603DE25AD4.
Error: listen EADDRINUSE: address already in use :::34884
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at EventedHTTPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:193:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:174:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
[2/5/2024, 4:20:02 PM] [SwitchBot] Child bridge process ended
[2/5/2024, 4:20:02 PM] [SwitchBot] Process Ended. Code: 1, Signal: null
[2/5/2024, 4:20:09 PM] [SwitchBot] Restarting Process...
[2/5/2024, 4:20:10 PM] [SwitchBot] Launched child bridge with PID 1233
[2/5/2024, 4:20:13 PM] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[2/5/2024, 4:20:13 PM] [SwitchBot] Loaded @switchbot/homebridge-switchbot v3.1.0 child bridge successfully
[2/5/2024, 4:20:13 PM] Loaded 2 cached accessories from cachedAccessories.0E603DE25AD4.
[2/5/2024, 4:20:13 PM] Homebridge v1.7.0 (HAP v0.11.1) (SwitchBot) is running on port 34884.
[2/5/2024, 4:20:13 PM] [SwitchBot] Total SwitchBot Devices Found: 2
[2/5/2024, 4:20:13 PM] [SwitchBot] Restoring existing accessory from cache: SwitchBot Bot DeviceID: D2353334687D
[2/5/2024, 4:20:13 PM] [SwitchBot] Restoring existing accessory from cache: Hub 2 51 DeviceID: E55460B62D51
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "correct token",
        "secret": "correct secret",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "64E833E4BE64",
                "configDeviceName": "SwitchBot Hub 2",
                "configDeviceType": "Hub 2",
                "lock": {
                    "activate_latchbutton": false
                },
                "history": true,
                "firmware": "1.5-1.0",
                "refreshRate": 360
            },
            {
                "deviceId": "D2353334687D",
                "configDeviceName": "SwitchBot Bot",
                "configDeviceType": "Bot",
                "connectionType": "OpenAPI",
                "bot": {
                    "mode": "press",
                    "deviceType": "door",
                    "allowPush": true,
                    "doublePress": 1
                },
                "lock": {
                    "activate_latchbutton": false
                },
                "firmware": "6.6",
                "refreshRate": 360,
                "external": false
            }
        ],
        "refreshRate": 360
    },
    "_bridge": {
        "username": "0E:60:3D:E2:5A:D4",
        "port": 34884
    },
    "platform": "SwitchBot"
}
```

### Device and Model

Synology DS 1819+

### Node.js Version

v18.19.0

### NPM Version

v?

### Homebridge Version

v1.7.0

### Homebridge Switchbot Plugin Version

v3.1.2

### Homebridge Config UI X Plugin Version

v4.55.1

### Operating System

Docker

**Comment by donavanbecker** [comment]
Can you try beta 3.2.0?

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.1.3-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by hansw1204** [comment]
v3.1.3-beta.2 works as expected.
Thank you for the quick fix!

From: Donavan Becker ***@***.***>
Date: Tuesday, February 6, 2024 at 00:58
To: OpenWonderLabs/homebridge-switchbot ***@***.***>
Cc: HaWi ***@***.***>, Author ***@***.***>
Subject: Re: [OpenWonderLabs/homebridge-switchbot] v3.1.2 leads to endless restart of child bridge. When restarting HomeBridge no plugins are loaded. (Issue #922)

Can you try the latest beta:

[npm ***@***.***/homebridge-switchbot>

Click here to find out how to install Beta<https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version>

**Comment by DanielZ3108** [comment]
Same problem for me but after a downgrade to 3.1.1 everything works again

[6.2.2024, 17:39:02] ====================
[6.2.2024, 17:39:02] ERROR LOADING PLUGIN @switchbot/homebridge-switchbot:
[6.2.2024, 17:39:02] file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/platform.js:36
import { SwitchBot } from 'node-switchbot';
         ^^^^^^^^^
SyntaxError: Named export 'SwitchBot' not found. The requested module 'node-switchbot' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'node-switchbot';
const { SwitchBot } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:429:15)
    at Plugin.load (/var/lib/homebridge/node_modules/homebridge/src/plugin.ts:227:40)
    at PluginManager.initializeInstalledPlugins (/var/lib/homebridge/node_modules/homebridge/src/pluginManager.ts:141:9)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:173:5)
[6.2.2024, 17:39:02] ====================

[6.2.2024, 17:39:02] No plugin was found for the platform "SwitchBot" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by donavanbecker** [comment]
3.1.3 has been released. Please try that before upgrade to 3.2.0
