### ISSUE TITLE
Feature Request: Add Humidifier's temperature/humidity sensors as an option when configuring an Air Conditioning (IR) device

### ISSUE THREAD

**Issue by lotfielhafi** [OpenWonderLabs/homebridge-switchbot#951]
### Problem

It is currently impossible to select/use the Humidifier temperature/humidity sensors when configuring the "Use an existing Switchbot device for temperature/humidity" field while configuring a Remote Type of Air Conditioning (IR) in the IR Device Settings panel.

<img width="701" alt="Screenshot 2024-03-12 at 12 42 23" src="https://github.com/OpenWonderLabs/homebridge-switchbot/assets/7369192/01e79c54-3623-4cca-b6cd-776637c24544">

### Solution

Add Humidifier as an option when configuring the "Use an existing Switchbot device for temperature/humidity" field while configuring a Remote Type of Air Conditioning (IR) in the IR Device Settings panel.

**Comment by donavanbecker** [comment]
v3.5.1 has been released, please install and let me know if this has been resolved.

**Comment by lotfielhafi** [comment]
@donavanbecker thank you so much for your help.

I have updated to v3.5.1 to test as instructed. However, I noticed that my SwitchBot child bridge is now stuck in a restart loop and cannot initialize properly. I have copied the log below. (My Node.js version is v20.15.0.)

```[29/06/2024, 11:31:42] [Homebridge 08A SwitchBot] Child bridge process ended
[29/06/2024, 11:31:42] [Homebridge 08A SwitchBot] Process Ended. Code: 1, Signal: null
[29/06/2024, 11:31:49] [Homebridge 08A SwitchBot] Restarting Process...
[29/06/2024, 11:31:51] [Homebridge 08A SwitchBot] Launched child bridge with PID 5599
[29/06/2024, 11:31:57] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[29/06/2024, 11:31:58] [Homebridge 08A SwitchBot] Loaded @switchbot/homebridge-switchbot v3.5.1 child bridge successfully
[29/06/2024, 11:31:58] Loaded 14 cached accessories from cachedAccessories.0E27F1E94C61.
[29/06/2024, 11:31:59] Homebridge v1.8.3 (HAP v0.12.2) (Homebridge 08A SwitchBot) is running on port 51549.
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Device: SwitchBot Evaporative Humidifier 01A with Device Type: Humidifier2, is currently not supported.
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Total SwitchBot Devices Found: 17
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Total IR Devices Found: 6
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Toshiba Plasmaion AC 09A deviceId: 02-202101011419-55277593
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Toshiba Plasmaion AC 04A deviceId: 02-202101011422-48680033
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Fujitsu J Series AC 15A deviceId: 02-202101011424-79397506
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Sharp Plasmacluster AC 08A deviceId: 02-202101011427-35257950
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Panasonic Eolia AC 11A deviceId: 02-202101011431-21823887
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Panasonic Eolia AC 01A deviceId: 02-202101011433-35890057
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 04A deviceId: 98CDAC5C1906
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 08A deviceId: 98CDACB1CD3E
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 09A deviceId: 98CDACB37786
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Lock 07A deviceId: C66770B2A26A
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Meter Plus 17A deviceId: D5B6231EF786
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Ceiling Light Pro 09A deviceId: DA45577F35EF
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Bot 05A deviceId: E8DA8E6AB72F
[29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Ceiling Light Pro 04A deviceId: F44E6DA161FD
TypeError: Cannot read properties of undefined (reading 'getService')
    at new AirConditioner (file:///usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/irdevice/airconditioner.ts:156:30)
    at SwitchBotPlatform.createAirConditioner (file:///usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:2037:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[29/06/2024, 11:32:02] [Homebridge 08A SwitchBot] Child bridge process ended
[29/06/2024, 11:32:02] [Homebridge 08A SwitchBot] Process Ended. Code: 1, Signal: null
[29/06/2024, 11:32:09] [Homebridge 08A SwitchBot] Restarting Process...
[29/06/2024, 11:32:11] [Homebridge 08A SwitchBot] Launched child bridge with PID 5642
[29/06/2024, 11:32:17] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[29/06/2024, 11:32:17] [Homebridge 08A SwitchBot] Loaded @switchbot/homebridge-switchbot v3.5.1 child bridge successfully
[29/06/2024, 11:32:17] Loaded 14 cached accessories from cachedAccessories.0E27F1E94C61.
[29/06/2024, 11:32:18] Homebridge v1.8.3 (HAP v0.12.2) (Homebridge 08A SwitchBot) is running on port 51549.
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Device: SwitchBot Evaporative Humidifier 01A with Device Type: Humidifier2, is currently not supported.
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Total SwitchBot Devices Found: 17
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Total IR Devices Found: 6
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Toshiba Plasmaion AC 09A deviceId: 02-202101011419-55277593
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Toshiba Plasmaion AC 04A deviceId: 02-202101011422-48680033
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Fujitsu J Series AC 15A deviceId: 02-202101011424-79397506
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Sharp Plasmacluster AC 08A deviceId: 02-202101011427-35257950
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Panasonic Eolia AC 11A deviceId: 02-202101011431-21823887
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Panasonic Eolia AC 01A deviceId: 02-202101011433-35890057
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 04A deviceId: 98CDAC5C1906
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 08A deviceId: 98CDACB1CD3E
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 09A deviceId: 98CDACB37786
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Lock 07A deviceId: C66770B2A26A
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Meter Plus 17A deviceId: D5B6231EF786
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Ceiling Light Pro 09A deviceId: DA45577F35EF
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Bot 05A deviceId: E8DA8E6AB72F
[29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Ceiling Light Pro 04A deviceId: F44E6DA161FD
TypeError: Cannot read properties of undefined (reading 'getService')
    at new AirConditioner (file:///usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/irdevice/airconditioner.ts:156:30)
    at SwitchBotPlatform.createAirConditioner (file:///usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:2037:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[29/06/2024, 11:32:22] [Homebridge 08A SwitchBot] Child bridge process ended
[29/06/2024, 11:32:22] [Homebridge 08A SwitchBot] Process Ended. Code: 1, Signal: null
[29/06/2024, 11:32:29] [Homebridge 08A SwitchBot] Restarting Process...```

**Comment by donavanbecker** [comment]
> @donavanbecker thank you so much for your help.
> 
> 
> 
> I have updated to v3.5.1 to test as instructed. However, I noticed that my SwitchBot child bridge is now stuck in a restart loop and cannot initialize properly. I have copied the log below. (My Node.js version is v20.15.0.)
> 
> 
> 
> ```[29/06/2024, 11:31:42] [Homebridge 08A SwitchBot] Child bridge process ended
> 
> [29/06/2024, 11:31:42] [Homebridge 08A SwitchBot] Process Ended. Code: 1, Signal: null
> 
> [29/06/2024, 11:31:49] [Homebridge 08A SwitchBot] Restarting Process...
> 
> [29/06/2024, 11:31:51] [Homebridge 08A SwitchBot] Launched child bridge with PID 5599
> 
> [29/06/2024, 11:31:57] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
> 
> [29/06/2024, 11:31:58] [Homebridge 08A SwitchBot] Loaded @switchbot/homebridge-switchbot v3.5.1 child bridge successfully
> 
> [29/06/2024, 11:31:58] Loaded 14 cached accessories from cachedAccessories.0E27F1E94C61.
> 
> [29/06/2024, 11:31:59] Homebridge v1.8.3 (HAP v0.12.2) (Homebridge 08A SwitchBot) is running on port 51549.
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Device: SwitchBot Evaporative Humidifier 01A with Device Type: Humidifier2, is currently not supported.
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Total SwitchBot Devices Found: 17
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Total IR Devices Found: 6
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Toshiba Plasmaion AC 09A deviceId: 02-202101011419-55277593
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Toshiba Plasmaion AC 04A deviceId: 02-202101011422-48680033
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Fujitsu J Series AC 15A deviceId: 02-202101011424-79397506
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Sharp Plasmacluster AC 08A deviceId: 02-202101011427-35257950
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Panasonic Eolia AC 11A deviceId: 02-202101011431-21823887
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Panasonic Eolia AC 01A deviceId: 02-202101011433-35890057
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 04A deviceId: 98CDAC5C1906
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 08A deviceId: 98CDACB1CD3E
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 09A deviceId: 98CDACB37786
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Lock 07A deviceId: C66770B2A26A
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Meter Plus 17A deviceId: D5B6231EF786
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Ceiling Light Pro 09A deviceId: DA45577F35EF
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Bot 05A deviceId: E8DA8E6AB72F
> 
> [29/06/2024, 11:32:01] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Ceiling Light Pro 04A deviceId: F44E6DA161FD
> 
> TypeError: Cannot read properties of undefined (reading 'getService')
> 
>     at new AirConditioner (file:///usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/irdevice/airconditioner.ts:156:30)
> 
>     at SwitchBotPlatform.createAirConditioner (file:///usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:2037:9)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> [29/06/2024, 11:32:02] [Homebridge 08A SwitchBot] Child bridge process ended
> 
> [29/06/2024, 11:32:02] [Homebridge 08A SwitchBot] Process Ended. Code: 1, Signal: null
> 
> [29/06/2024, 11:32:09] [Homebridge 08A SwitchBot] Restarting Process...
> 
> [29/06/2024, 11:32:11] [Homebridge 08A SwitchBot] Launched child bridge with PID 5642
> 
> [29/06/2024, 11:32:17] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
> 
> [29/06/2024, 11:32:17] [Homebridge 08A SwitchBot] Loaded @switchbot/homebridge-switchbot v3.5.1 child bridge successfully
> 
> [29/06/2024, 11:32:17] Loaded 14 cached accessories from cachedAccessories.0E27F1E94C61.
> 
> [29/06/2024, 11:32:18] Homebridge v1.8.3 (HAP v0.12.2) (Homebridge 08A SwitchBot) is running on port 51549.
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Device: SwitchBot Evaporative Humidifier 01A with Device Type: Humidifier2, is currently not supported.
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Total SwitchBot Devices Found: 17
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Total IR Devices Found: 6
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Toshiba Plasmaion AC 09A deviceId: 02-202101011419-55277593
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Toshiba Plasmaion AC 04A deviceId: 02-202101011422-48680033
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Fujitsu J Series AC 15A deviceId: 02-202101011424-79397506
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Sharp Plasmacluster AC 08A deviceId: 02-202101011427-35257950
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Panasonic Eolia AC 11A deviceId: 02-202101011431-21823887
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: Panasonic Eolia AC 01A deviceId: 02-202101011433-35890057
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 04A deviceId: 98CDAC5C1906
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 08A deviceId: 98CDACB1CD3E
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Humidifier 09A deviceId: 98CDACB37786
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Lock 07A deviceId: C66770B2A26A
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Meter Plus 17A deviceId: D5B6231EF786
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Ceiling Light Pro 09A deviceId: DA45577F35EF
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Bot 05A deviceId: E8DA8E6AB72F
> 
> [29/06/2024, 11:32:21] [Homebridge 08A SwitchBot] Restoring existing accessory from cache: SwitchBot Ceiling Light Pro 04A deviceId: F44E6DA161FD
> 
> TypeError: Cannot read properties of undefined (reading 'getService')
> 
>     at new AirConditioner (file:///usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/irdevice/airconditioner.ts:156:30)
> 
>     at SwitchBotPlatform.createAirConditioner (file:///usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:2037:9)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> [29/06/2024, 11:32:22] [Homebridge 08A SwitchBot] Child bridge process ended
> 
> [29/06/2024, 11:32:22] [Homebridge 08A SwitchBot] Process Ended. Code: 1, Signal: null
> 
> [29/06/2024, 11:32:29] [Homebridge 08A SwitchBot] Restarting Process...```


For this issue, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.5.2-beta.1/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
As far as humidifier, I will work on getting that added

**Comment by donavanbecker** [comment]
v3.6.0 has been released with Humidifier as a meterType
