### ISSUE TITLE
Bug: Switchbot child bridge keeps crashing

### ISSUE THREAD

**Issue by Jacksonbm1** [OpenWonderLabs/homebridge-switchbot#955]
### Describe the Bug

I am running the plugin and had no issues till a few days ago. After,  I tried updating and I got the errors (I didn't check the logs before updating, but it def wasn't working properly).

### To Reproduce

Just run the plugin and it will start crashing

here's my config though I redacted all the personal stuff:

### Expected Behavior

should work and not crash?

### Relevant Log Output

```shell
[3/17/2024, 9:45:14 PM] [SwitchBot] Restarting Process...
[3/17/2024, 9:45:15 PM] [SwitchBot] Launched child bridge with PID 15078
[3/17/2024, 9:45:20 PM] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[3/17/2024, 9:45:20 PM] [SwitchBot] Loaded @switchbot/homebridge-switchbot v3.4.0 child bridge successfully
[3/17/2024, 9:45:20 PM] Loaded 7 cached accessories from cachedAccessories.0E3225FEF6CB.
Error: listen EADDRINUSE: address already in use :::56266
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at EventedHTTPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
[3/17/2024, 9:45:21 PM] [SwitchBot] Child bridge process ended
[3/17/2024, 9:45:21 PM] [SwitchBot] Process Ended. Code: 1, Signal: null
[3/17/2024, 9:45:28 PM] [SwitchBot] Restarting Process...
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "<REDACTED>",
                "secret": "<REDACTED>",
                "notice": "Keep your Token & Secret a secret!"
            },
            "_bridge": {
                "username": "<REDACTED>",
                "port": <REDACTED>
            },
            "platform": "SwitchBot"
        }
```

### Screenshots

<img width="791" alt="image" src="https://github.com/OpenWonderLabs/homebridge-switchbot/assets/39594156/06b5b9b2-023a-487d-aac8-1ff117334789">

### Device and Model

Raspberry Pi 4B+

### Node.js Version

v18.19.0

### NPM Version

10.2.3

### Homebridge Version

1.7.0

### Homebridge Switchbot Plugin Version

v3.4.0

### Homebridge Config UI X Plugin Version

v4.55.1

### Operating System

Rasbian

**Comment by Jacksonbm1** [comment]
issue seems to have disappeared. No idea why, but will mark as closed for now and monitor
