### ISSUE TITLE
Bug: Homebridge shuts down. If there is a ceiling light.

### ISSUE THREAD

**Issue by sinsin-san** [OpenWonderLabs/homebridge-switchbot#982]
### Describe the Bug

If there is a ceiling light, the home bridge shuts down.

### To Reproduce

- Prerequisite.
Register the ceiling light in Switchbot account.

- Procedure
1. Install the SwitchBot plugin.
2. Install Token and Secret.
3. HomeBridge repeatedly shuts down.

### Expected Behavior

The home bridge must be able to be used without shutting down and with ceiling lights.

### Relevant Log Output

```shell
[06/06/2024, 06:07:56] TypeError: Cannot read properties of undefined (reading 'bName')
    at new CeilingLight (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/ceilinglight.ts:55:40)
    at SwitchBotPlatform.createCeilingLight (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:1744:7)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/06/2024, 06:07:56] TypeError: Cannot read properties of undefined (reading 'bName')
    at new CeilingLight (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/ceilinglight.ts:55:40)
    at SwitchBotPlatform.createCeilingLight (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:1744:7)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/06/2024, 06:07:56] TypeError: Cannot read properties of undefined (reading 'bName')
    at new CeilingLight (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/ceilinglight.ts:55:40)
    at SwitchBotPlatform.createCeilingLight (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:1744:7)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/06/2024, 06:07:56] TypeError: Cannot read properties of undefined (reading 'bName')
    at new CeilingLight (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/ceilinglight.ts:55:40)
    at SwitchBotPlatform.createCeilingLight (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:1744:7)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/06/2024, 06:07:56] Got SIGTERM, shutting down Homebridge...
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "******",
        "secret": "******",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "logging": "debug"
    },
    "platform": "SwitchBot"
}
```

### Device and Model

Raspberry Pi 3b+

### Node.js Version

v18.16.0

### NPM Version

no

### Homebridge Version

v1.8.2

### Homebridge Switchbot Plugin Version

v3.5.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
I will get this resolved in the next release. Can you try a previous release?

**Comment by sinsin-san** [comment]
Thank you for your reply and suggestions.
The issue did not occur with v3.4.0, so I will use it until it is resolved.

**Comment by donavanbecker** [comment]
v3.5.1 has been released, please install and let me know if this has been resolved.

**Comment by sinsin-san** [comment]
I tried it with v3.5.1 and was able to confirm that it works as expected.
Thank you for fixing it.
