### ISSUE TITLE
Bug: IR Air Conditioning will not turn on anymore, but off still works

### ISSUE THREAD

**Issue by JeredBlu** [OpenWonderLabs/homebridge-switchbot#983]
### Describe the Bug

I have the hub mini with four switchbot curtains, a one bot. Everything was working fine for a while. 
For the last few months, the air conditioner (which is an IR device controlled by hub mini) would always display as on, even if it was turned off via HomeKit, it didnt bug me. 

For the last week, the action of turning on the air conditioner doesnt work, not via Siri, not via the home app, it still shows as on all the time, and even when it shows as off, I am not able to turn it on. 

Interestingly enough, I am able to turn it off with apple home. 

Homebridge is on the latest version, as well as nodejs (just upgraded it hoping it would solve this). 

The air conditioning works great with the switchbot app.

Other things ive noticed:
The bot works now only sometimes

### To Reproduce

Pressing the AC button in home app or via Siri and setting it to on

### Expected Behavior

That the AC will turn on

### Relevant Log Output.

Please not that at 1:02 I reset the router, that is the reason for the connectivity issues

```shell
[07/06/2024, 15:04:24] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"} sent successfully
[07/06/2024, 17:00:02] [SwitchBot] Bot: Dude Set ProgrammableSwitchOutputState: true
[07/06/2024, 19:45:34] [SwitchBot] Curtain: Living Room Curtain request to SwitchBot API, body: {"command":"setPosition","parameter":"0,ff,100","commandType":"command"} sent successfully
[07/06/2024, 19:45:34] [SwitchBot] Curtain3: Bedroom Curtains request to SwitchBot API, body: {"command":"setPosition","parameter":"0,ff,100","commandType":"command"} sent successfully
[07/06/2024, 22:26:07] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"},
[07/06/2024, 22:26:08] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"} sent successfully
[07/06/2024, 22:26:09] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"setAll","parameter":"13,2,1,on","commandType":"command"},
[07/06/2024, 22:26:09] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"setAll","parameter":"13,2,1,on","commandType":"command"} sent successfully
[07/06/2024, 22:33:36] [SwitchBot] Bot: Dude Set ProgrammableSwitchOutputState: false
[07/06/2024, 23:03:40] [SwitchBot] Bot: Dude Set ProgrammableSwitchOutputState: false
[07/06/2024, 23:31:48] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"},
[07/06/2024, 23:31:49] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"} sent successfully
[07/06/2024, 23:31:49] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"setAll","parameter":"13,2,1,on","commandType":"command"},
[07/06/2024, 23:31:50] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"setAll","parameter":"13,2,1,on","commandType":"command"} sent successfully
[07/06/2024, 23:33:58] [SwitchBot] Bot: Dude Set ProgrammableSwitchOutputState: false
[07/06/2024, 23:57:07] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"},
[07/06/2024, 23:57:08] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"} sent successfully
[08/06/2024, 00:04:02] [SwitchBot] Bot: Dude Set ProgrammableSwitchOutputState: false
[08/06/2024, 00:34:18] [SwitchBot] Bot: Dude Set ProgrammableSwitchOutputState: false
[08/06/2024, 00:47:35] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"},
[08/06/2024, 00:47:36] [SwitchBot] Air Conditioner: Air Conditioner Hub Device is offline, statusCode: 171. Hub: F0C7AECB782A
[08/06/2024, 00:47:37] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"setAll","parameter":"13,2,1,on","commandType":"command"},
[08/06/2024, 00:47:37] [SwitchBot] Air Conditioner: Air Conditioner Hub Device is offline, statusCode: 171. Hub: F0C7AECB782A
[08/06/2024, 01:00:18] [SwitchBot] Initializing SwitchBot platform...
[08/06/2024, 01:00:21] [SwitchBot] Total SwitchBot Devices Found: 7
[08/06/2024, 01:00:21] [SwitchBot] Restoring existing accessory from cache: Air Conditioner DeviceID: 02-202310311622-33061895
[08/06/2024, 01:00:21] [SwitchBot] Total IR Devices Found: 2
[08/06/2024, 01:00:21] [SwitchBot] Restoring existing accessory from cache: Bot FD DeviceID: F010B5C344FD
[08/06/2024, 01:00:21] [SwitchBot] Restoring existing accessory from cache: Dude DeviceID: F03A2A322FA6
[08/06/2024, 01:00:21] [SwitchBot] Restoring existing accessory from cache: Living Room Curtain DeviceID: E587C64DBB3F
[08/06/2024, 01:00:21] [SwitchBot] Bot: Bot FD does not have bot mode set in the Plugin's SwitchBot Device Settings,
[08/06/2024, 01:00:21] [SwitchBot] Bot: Bot FD is defaulting to "switch" mode, you may experience issues.
[08/06/2024, 01:00:21] [SwitchBot] Restoring existing accessory from cache: Bedroom Curtains DeviceID: F8A21F7C6C9E
[08/06/2024, 01:00:22] Sony Soundbar E0A5 is running on port 38949.
[08/06/2024, 01:00:22] Please add [Sony Soundbar E0A5] manually in Home app. Setup Code: 711-29-109
[08/06/2024, 01:01:14] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"},
[08/06/2024, 01:01:15] [SwitchBot] Air Conditioner: Air Conditioner Hub Device is offline, statusCode: 171. Hub: F0C7AECB782A
[08/06/2024, 01:01:16] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"setAll","parameter":"13,2,1,on","commandType":"command"},
[08/06/2024, 01:01:16] [SwitchBot] Air Conditioner: Air Conditioner Hub Device is offline, statusCode: 171. Hub: F0C7AECB782A
[08/06/2024, 01:02:21] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:21] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:21] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:22] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:24] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:24] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:24] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
Error: TIMEOUT
    at /var/lib/homebridge/node_modules/homebridge-red-alert-via-kumta/node_modules/telegram/client/updates.js:244:85
    at _updateLoop (/var/lib/homebridge/node_modules/homebridge-red-alert-via-kumta/node_modules/telegram/client/updates.js:187:17)
[2024-06-08T01:02:26.429] [INFO] - [Started reconnecting]
[2024-06-08T01:02:26.430] [WARN] - [[Reconnect] Closing current connection...]
[2024-06-08T01:02:26.431] [INFO] - [Disconnecting from 149.154.175.60:80/TCPFull...]
[2024-06-08T01:02:26.432] [WARN] - [Connection closed while receiving data]
Error: Not connected
    at ConnectionTCPFull.recv (/var/lib/homebridge/node_modules/homebridge-red-alert-via-kumta/node_modules/telegram/network/connection/Connection.js:71:15)
    at MTProtoSender._recvLoop (/var/lib/homebridge/node_modules/homebridge-red-alert-via-kumta/node_modules/telegram/network/MTProtoSender.js:362:24)
[2024-06-08T01:02:26.436] [INFO] - [Connecting to 149.154.175.60:80/TCPFull...]
[2024-06-08T01:02:26.437] [INFO] - [connection closed]
[08/06/2024, 01:02:35] [SwitchBot] Error making request: Connect Timeout Error
[2024-06-08T01:02:36.716] [ERROR] - [WebSocket connection failed attempt: 1]
Error: connect EHOSTUNREACH 149.154.175.60:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '149.154.175.60',
  port: 80
}
[2024-06-08T01:02:37.723] [INFO] - [Connecting to 149.154.175.60:80/TCPFull...]
[08/06/2024, 01:02:37] [SwitchBot] Error making request: Connect Timeout Error
[08/06/2024, 01:02:37] [SwitchBot] Error making request: Connect Timeout Error
[08/06/2024, 01:02:37] [SwitchBot] Error making request: Connect Timeout Error
[08/06/2024, 01:02:41] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:41] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:41] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:41] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:44] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:44] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:44] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:44] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:47] [SwitchBot] Bot: Bot FD failed openAPIRefreshStatus with OpenAPI Connection, Error Message: "Cannot read properties of null (reading 'json')"
[08/06/2024, 01:02:47] [SwitchBot] Error making request: getaddrinfo ENOTFOUND api.switch-bot.com
[08/06/2024, 01:02:47] [SwitchBot] Bot: Dude failed openAPIRefreshStatus with OpenAPI Connection, Error Message: "Cannot read properties of null (reading 'json')"
[08/06/2024, 01:02:47] [SwitchBot] Curtain: Living Room Curtain failed openAPIRefreshStatus with OpenAPI Connection, Error Message: "Cannot read properties of null (reading 'json')"
[08/06/2024, 01:02:50] [SwitchBot] Curtain3: Bedroom Curtains failed openAPIRefreshStatus with OpenAPI Connection, Error Message: "Cannot read properties of null (reading 'json')"
[08/06/2024, 01:04:28] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"},
[08/06/2024, 01:04:29] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"} sent successfully
[08/06/2024, 01:04:32] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"},
[08/06/2024, 01:04:32] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"} sent successfully
[08/06/2024, 01:04:33] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"setAll","parameter":"13,2,1,on","commandType":"command"},
[08/06/2024, 01:04:34] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"setAll","parameter":"13,2,1,on","commandType":"command"} sent successfully
[08/06/2024, 01:09:50] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"},
[08/06/2024, 01:09:51] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"} sent successfully
[08/06/2024, 01:10:26] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"},
[08/06/2024, 01:10:26] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"} sent successfully
[08/06/2024, 01:10:29] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"},
[08/06/2024, 01:10:29] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"} sent successfully
[08/06/2024, 01:10:43] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"},
[08/06/2024, 01:10:43] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"} sent successfully
[08/06/2024, 01:10:44] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"setAll","parameter":"13,2,1,on","commandType":"command"},
[08/06/2024, 01:10:45] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"setAll","parameter":"13,2,1,on","commandType":"command"} sent successfully
[08/06/2024, 01:10:51] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"},
[08/06/2024, 01:10:52] [SwitchBot] Air Conditioner: Air Conditioner request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"} sent successfully
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
    "credentials": {
        "token": "***",
        "secret": "***",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "*",
                "configDeviceName": "Dude",
                "configDeviceType": "Bot",
                "connectionType": "OpenAPI",
                "bot": {
                    "mode": "switch",
                    "deviceType": "switch"
                },
                "logging": "standard"
            },
            {
                "deviceId": "*",
                "configDeviceName": "Living Room Curtain",
                "configDeviceType": "Curtain",
                "connectionType": "OpenAPI",
                "curtain": {
                    "hide_lightsensor": true
                }
            },
            {
                "deviceId": "*",
                "configDeviceName": "Bedroom Curtains",
                "configDeviceType": "Curtain3",
                "connectionType": "OpenAPI"
            }
        ]
    },
    "platform": "SwitchBot"
}
```

### Screenshots

<img width="205" alt="image" src="https://github.com/OpenWonderLabs/homebridge-switchbot/assets/16615521/2aec6907-a41b-40b1-8dee-70dbf6883c0b">

### Device and Model

Switchbot Hub Mini

### Node.js Version

v20.14.0

### NPM Version

10.7.0

### Homebridge Version

v1.8.2

### Homebridge Switchbot Plugin Version

v3.5.0

### Homebridge Config UI X Plugin Version

v4.56.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Revert to 3.4.x until I have time to push out an update

**Comment by JeredBlu** [comment]
Ok so I have an update, first I tried reverting to both 3.4.0 and 3.3.0 but the problem persisted...

I noticed that in the homebridge logs, the turning on command was "setall", its summer so we never use the "heat" function, and I never use the "auto" function, in any case I toggled each of them, and eventually the 'auto' function turned the AC on... When I went back to the "cool" function it turned on... so something with the "auto" state seems to have confused the system.

Now I reupdated to 3.5.0 and it seems to be working.

That being said, it still will think in the home app that the air conditioner is on, immediately after turning it off, so it still is a problem to turn it on. 





. On Jun 8, 2024, at 3:13 AM, Donavan Becker ***@***.***> wrote:﻿
Revert to 3.4.x until I have time to push out an update

**Comment by JrodbTG** [comment]
@donavanbecker showing you how it behaves
![59176d03-6686-4021-8d95-be3dad18cb35](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/16615521/dbd97d34-f307-468a-a2a3-b0599fb3bf55)

**Comment by JeredBlu** [comment]
@donavanbecker 
Sorry made a mistake, this isnt closed, here is a video of the problem
![59176d03-6686-4021-8d95-be3dad18cb35](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/16615521/c0aebfed-6e61-476e-a16d-089fbc58372a)

**Comment by donavanbecker** [comment]
v3.5.1 has been released, please install and let me know if this has been resolved.

**Comment by JeredBlu** [comment]
@donavanbecker it seems to be resolved, thanks! 
I am noticing many error messages in the console upon requests.. sometimes the requests work, sometimes they dont:

RangeError: Maximum call stack size exceeded
[05/07/2024, 11:30:20] [SwitchBot] Air Conditioner: Air Conditioner failed pushChanges with OpenAPI Connection, Error Message: "Maximum call stack size exceeded"
[05/07/2024, 11:31:32] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"},
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
                          ^
RangeError: Maximum call stack size exceeded
[05/07/2024, 11:31:33] [SwitchBot] Air Conditioner: Air Conditioner failed pushChanges with OpenAPI Connection, Error Message: "Maximum call stack size exceeded"
[05/07/2024, 11:31:34] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"setAll","parameter":"24,2,1,on","commandType":"command"},
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
                          ^
RangeError: Maximum call stack size exceeded
[05/07/2024, 11:31:34] [SwitchBot] Air Conditioner: Air Conditioner failed pushChanges with OpenAPI Connection, Error Message: "Maximum call stack size exceeded"
[05/07/2024, 11:45:16] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"},
[05/07/2024, 11:45:17] [SwitchBot] Air Conditioner: Air Conditioner failed pushChanges with OpenAPI Connection, Error Message: "Maximum call stack size exceeded"
[05/07/2024, 13:05:13] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"},
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
                          ^
RangeError: Maximum call stack size exceeded
[05/07/2024, 13:05:14] [SwitchBot] Air Conditioner: Air Conditioner failed pushChanges with OpenAPI Connection, Error Message: "Maximum call stack size exceeded"
[05/07/2024, 13:05:14] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"setAll","parameter":"24,2,1,on","commandType":"command"},
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
                          ^
RangeError: Maximum call stack size exceeded
[05/07/2024, 13:05:15] [SwitchBot] Air Conditioner: Air Conditioner failed pushChanges with OpenAPI Connection, Error Message: "Maximum call stack size exceeded"
[05/07/2024, 13:21:29] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOff","parameter":"default","commandType":"command"},
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
                          ^
RangeError: Maximum call stack size exceeded
[05/07/2024, 13:21:30] [SwitchBot] Air Conditioner: Air Conditioner failed pushChanges with OpenAPI Connection, Error Message: "Maximum call stack size exceeded"
[05/07/2024, 13:47:34] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"setAll","parameter":"24,2,1,off","commandType":"command"},
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
                          ^
RangeError: Maximum call stack size exceeded
[05/07/2024, 13:47:35] [SwitchBot] Air Conditioner: Air Conditioner failed pushChanges with OpenAPI Connection, Error Message: "Maximum call stack size exceeded"
[05/07/2024, 13:47:52] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"turnOn","parameter":"default","commandType":"command"},
[05/07/2024, 13:47:53] [SwitchBot] Air Conditioner: Air Conditioner Sending request to SwitchBot API, body: {"command":"setAll","parameter":"24,2,1,on","commandType":"command"},
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
                          ^
RangeError: Maximum call stack size exceeded
[05/07/2024, 13:47:54] [SwitchBot] Air Conditioner: Air Conditioner failed pushChanges with OpenAPI Connection, Error Message: "Maximum call stack size exceeded"
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/dist/irdevice/irdevice.js:171
        return await this.successfulStatusCodes(statusCode, deviceStatus);
                          ^
RangeError: Maximum call stack size exceeded
[05/07/2024, 13:47:54] [SwitchBot] Air Conditioner: Air Conditioner failed pushChanges with OpenAPI Connection, Error Message: "Maximum call stack size exceeded"

**Comment by donavanbecker** [comment]
this should be resolved in the latest beta.
